(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.QE65Q80R = function() {
	this.initialize(img.QE65Q80R);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,300,189);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACpCyQgtgpAAhRIAAkUIBqAAIAAENQAAAtAQAWQARAXAlAAQAkAAASgWQARgVAAgvIAAkNIBqAAIAAEUQAABQgtAqQgsArhYAAQhVgBgugqgAgeDTIh2ieIgmAAIAACeIhpAAIAAmvICqAAQAjABAaAEQAZAEAXAPQAWAOANAYQANAVAAAkQAAAygVAfQgVAeglASICNC3gAi6gXIAfAAQAWAAAPgEQAPgCALgJQAKgIAGgLQAFgNAAgRQAAgQgGgMQgHgMgOgGQgKgFgMgBQgMgBgSAAIgkAAgAncDTIAAhyIBlAAIAAByg");
	this.shape.setTransform(433.3,23);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AqSClQg3g+AAhmQAAhnA3g+QA2g8BgAAQBfAAA3A8QA3A9AABoQAABng3A9Qg2A8hgAAQhgAAg2g8gAofiHQgQAHgPASQgNARgIAcQgIAbAAAnQAAAoAHAaQAIAZANATQAPASAQAHQASAIASgBQATAAASgHQARgIANgSQAOgTAHgZQAHgbAAgnQAAgmgHgbQgJgbgMgRQgOgSgRgIQgRgHgTAAQgVAAgOAHgA2gClQg2g9AAhnQAAhoA2g9QA3g8BgAAQBfAAA3A8QA3A9AABoQAABng3A9Qg3A8hfAAQhgAAg3g8gA0tiHQgQAHgOASQgNAQgJAdQgIAeAAAkQAAAoAIAaQAIAZANATQAOASARAHQASAIASgBQATAAARgHQASgJANgRQANgTAIgZQAHgaAAgoQAAgkgIgdQgHgbgOgRQgNgSgRgIQgRgHgTAAQgVAAgPAHgAb7DZIh0ixIgUAeIAACTIhrAAIAAmwIBrAAIAADAICHjAIB7AAIiXDJICdDngATeDZIAAhMIA9AAIAAkYIg9AAIAAhMIDkAAIAABMIg9AAIAAEYIA9AAIAABMgAQzDZIijktIAAEtIhiAAIAAmwICDAAICHD2IAAj2IBhAAIAAGwgAHhDZIAAmwIBrAAIAAFdICwAAIAABTgAC3DZIAAhMIA9AAIAAkYIg9AAIAAhMIDkAAIAABMIg9AAIAAEYIA9AAIAABMgAjwDZIAAmwICDAAQAtAAAnAGQAmAGAiAWQAqAcAYAtQAYAwAAA9QAAA7gaAxQgaAwgnAZQgiAWglAGQgqAHgpAAgAiGCIIACAAQAkAAAZgCQAZgBAVgOQAagRANgeQAOgdAAgrQAAgqgOgeQgOgegegSQgWgMgXgBIg7gBgAv9DZIAAmwIBqAAIAAFdICwAAIAABTgA6ADZIAAjAIiQAAIAADAIhqAAIAAmwIBqAAIAACeICQAAIAAieIBrAAIAAGwg");
	this.shape_1.setTransform(191.5,22.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AOkBPQgTgVAAgjQAAgiATgVQAUgVAhAAQAhAAAUAVQATAVAAAiQAAAkgTAUQgTAVgiAAQgiAAgTgVgAPNgWQgFACgGAGQgEAGgDAJQgDAJgBANQABAOADAJQABAIAGAHQAFAGAGACQAFADAHABQAHgBAGgDQAGgCAFgHQAFgGACgIQACgJABgOQgBgNgCgJQgDgJgEgFQgFgGgGgDQgHgDgGAAQgGAAgGADgAJdBPQgSgVAAgjQAAgiASgVQAUgVAiAAQAhAAAUAVQASAVABAiQgBAkgSAUQgUAVghAAQgjAAgTgVgAKGgWQgGACgFAGQgFAGgCAJQgDAJAAANQAAANACAKQADAJAFAGQAGAGAFACQAGADAHABQAGgBAGgDQAHgCAEgHQAEgGADgIQADgJAAgOQAAgNgDgJQgDgJgEgFQgFgHgGgCQgHgDgFAAQgHAAgGADgAnKBhQgRgDgIgDIAAghIAEAAQAJAFALAFQANAEAKABQAPAAAKgGQAJgFAAgMQgBgJgGgFQgHgEgQgBIgWAAIAAgaIAUAAQAOAAAHgEQAHgEgBgIQAAgIgGgDQgIgDgLAAQgHAAgHACIgLADIgKAEIgHAEIgDAAIAAgfIAVgGQARgEANAAQAcAAAPAKQAPAJAAARQAAANgIAIQgHAJgNADIAAABQAGACAFACQAFADAFADQAGAFACAGQADAGAAAJQAAAXgSALQgQANggAAQgNAAgPgDgEAlAABhIAAhhIg5BhIgiAAIAAiTIAkAAIAABYIA1hYIAnAAIAACTgEAieABhIgpg7IgJAAIAAA7IgmAAIAAiTIAmAAIAAA8QAKgCADgDQAEgCAHgMIAIgQQAFgNALgHQAIgFAQAAIAOAAIAAAgIgJAAQgIAAgDAEQgGAFgEAKQgEAJgDAEQgDAFgEACIA0BMgAf1BhIAAhhIg4BhIgjAAIAAiTIAlAAIAABYIA1hYIAmAAIAACTgAdHBhIAAhCIgzAAIAABCIglAAIAAiTIAlAAIAAA2IAzAAIAAg2IAmAAIAACTgAanBhIgcgvIgdAvIgqAAIAwhKIguhJIArAAIAbAtIAcgtIApAAIgvBHIAxBMgAXIBhIAAiTIBlAAIAAAcIhAAAIAAAaIA7AAIAAAbIg7AAIAAAmIBAAAIAAAcgAVaBhIAAh3IgtAAIAAgcIB+AAIAAAcIgsAAIAAB3gAShBhIAAhhIg5BhIgjAAIAAiTIAlAAIAABYIA1hYIAnAAIAACTgAL/BhIAAiTIA1AAQAPAAAKABQAHABAIAFQAIAEAEAHQAEAGAAALQAAALgGAHQgEAIgKAEIAAABQANADAIAJQAJAJAAAPQAAAKgEAJQgEAJgIAFQgHAGgLADQgLADgOAAgAMkBGIAXAAQAHgBAEgCQAFgCACgFQACgEABgFQAAgHgDgEQgDgDgFgDQgEgBgGAAIgXAAgAMkAHIASAAIAIgCQAFgCACgDQABgDAAgFIgBgHQgDgFgEgBQgDgCgFABIgSgBgAHkBhIAAh3IgsAAIAAgcIB+AAIAAAcIgsAAIAAB3gAF1BhIAAiTIAlAAIAACTgAD1BhIAAiTIAlAAIAAA3IAXAAQAJgBAOACQAKACAJAHQAHAGAFAJQADAJAAALQAAAJgEALQgFAKgHAFQgJAHgJACQgLADgOAAgAEaBFIARAAQAMABAGgFQAHgGAAgIIgBgHQgCgEgCgCQgCgDgGgCQgEgBgIAAIgRAAgABaBhIAAiTIBsAAIAAAcIhHAAIAAAbIAZAAQAJgBAOACQAMADAHAGQAIAGAEAJQADAKAAAKQAAAKgEAKQgEAJgHAGQgJAHgKACQgLADgNAAgAB/BFIATAAQAMABAGgFQAHgGAAgIIgBgHQgBgEgDgCQgDgDgEgCQgEgBgJAAIgTAAgAhCBhIAAhCIgyAAIAABCIgmAAIAAiTIAmAAIAAA2IAyAAIAAg2IAlAAIAACTgAjrBhIAAhhIg6BhIgiAAIAAiTIAlAAIAABYIA0hYIAoAAIAACTgAobBhIgJgeIgvAAIgKAeIglAAIAziTIAoAAIAyCTgApLAoIAfAAIgQgvgAr0BhIAAiTIBlAAIAAAcIg/AAIAAB3gAs4BhIgJgeIguAAIgJAeIgmAAIAyiTIApAAIAyCTgAtnAoIAeAAIgPgvgAvhBhIAAhhIgbA+IgZAAIgbg+IAABhIgjAAIAAiTIArAAIAhBIIAhhIIAqAAIAACTgA0MBhIAAh3IgtAAIAAgcIB+AAIAAAcIgsAAIAAB3gA22BhIAAiTIBlAAIAAAcIg/AAIAAAaIA7AAIAAAbIg7AAIAAAmIA/AAIAAAcgA4IBhIAAhCIgzAAIAABCIglAAIAAiTIAlAAIAAA2IAzAAIAAg2IAlAAIAACTgA71BhIAAiTIA6AAQAMAAAKACQAJACAIAGQAJAGAEAJQAFAJgBANQAAAKgDAIQgEALgFAFIgJAIIgJAFIgMAEIgPABIgTAAIAAAwgA7PAVIAUAAIAHgCIAFgEQADgEACgEQACgDgBgHQAAgFgCgFQgDgEgFgDIgKgCIgSAAgA+BBhIAAiTIBkAAIAAAcIg/AAIAAAaIA7AAIAAAbIg7AAIAAAmIA/AAIAAAcgA/wBhIAAh3IgsAAIAAgcIB+AAIAAAcIgsAAIAAB3gEghfABhIAAhCIgzAAIAABCIglAAIAAiTIAlAAIAAA2IAzAAIAAg2IAmAAIAACTgEgkIABhIAAhhIg6BhIgiAAIAAiTIAlAAIAABYIA0hYIAnAAIAACTgAy+AjIAAgVIBGAAIAAAVgARfhGQgNgLAAgSIAgAAQAAALAFAFQAEAFALAAQALAAAEgFQAFgFAAgLIAhAAQAAASgNALQgNALgbAAQgaAAgNgLg");
	this.shape_2.setTransform(240.5,58.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,481,68.5), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAlIgHgDIgFgEIgFgGIAHgEQADAFAEACQAFADAEAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIAAgGIAEgBIAFgCIADgEIABgFQAAgGgDgDQgEgDgGAAQgEAAgEACQgDADgCAEIgHgEQADgHAGgDQAGgDAGAAQAEAAAEABIAHAEQADACACAEQACADAAAFQAAAGgDAEQgEAEgEACIAEACIAEADIADAFIABAHQAAAFgCAEQgCAEgEADQgDADgFABIgIABIgGAAg");
	this.shape.setTransform(176.3,29.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAlIgHgDIgFgEIgFgGIAHgEQADAFAEACQAFADAEAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIAAgGIAEgBIAFgCIADgEIABgFQAAgGgDgDQgEgDgGAAQgEAAgEACQgDADgCAEIgHgEQADgHAGgDQAGgDAGAAQAEAAAEABIAHAEQADACACAEQACADAAAFQAAAGgDAEQgEAEgEACIAEACIAEADIADAFIABAHQAAAFgCAEQgCAEgEADQgDADgFABIgIABIgGAAg");
	this.shape_1.setTransform(170.5,29.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNAiQgGgDgDgGIAHgEQAEAIALAAQAGAAAEgEQAEgEABgIQgBgIgGgFQgHgEgLABIgJAAIAAghIAmAAIAAAIIgdAAIAAARIABAAIAMABQAGABAFAEQADADADADQADAFAAAHQAAAGgCAFQgCAEgDADQgEADgEABQgEABgEAAQgHAAgGgCg");
	this.shape_2.setTransform(164.9,29.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUAlIAAgFIAMgOIAJgMIAEgGIAEgFIACgFIABgFQAAgGgDgEQgEgDgFAAQgJAAgGALIgHgEQAEgHAFgEQAGgEAIAAQAEAAAEACIAHAEIAEAGIABAIQAAAHgDAGIgJALIgJALIgIAKIAfAAIAAAIg");
	this.shape_3.setTransform(158.9,29.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLAkIAag/IgnAAIAAgIIAxAAIAAAGIgaBBg");
	this.shape_4.setTransform(153.1,29.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQAfIAJgEIAHgFQAFgCADgEIAEgIIgGACIgHABQgFAAgEgCIgHgFIgDgHQgCgEAAgFQAAgFACgFQABgEADgDIAHgFQAEgCAFAAQAFAAAFACQAEADADAEIAFAJQABAFAAAGQAAAIgDAHQgDAIgEAGQgGAGgHAEQgFAEgJABgAgGgbIgEADIgDAGIAAAGIAAAGIADAGIAEADQADABADAAIAHgBIAGgDIABgHIgBgIIgCgHIgEgFQgDgCgEAAQgEAAgCACg");
	this.shape_5.setTransform(147.3,29.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgQAfIAJgEIAHgFQAFgCACgEIAFgIIgGACIgGABQgGAAgEgCIgHgFIgDgHQgCgEAAgFQAAgFACgFQABgEADgDIAHgFQAEgCAFAAQAFAAAFACQAEADADAEIAFAJQABAFAAAGQAAAIgDAHQgDAIgEAGQgGAGgHAEQgFAEgJABgAgGgbIgEADIgDAGIAAAGIAAAGIADAGIAEADQADABADAAIAHgBIAGgDIABgHIgBgIIgCgHIgEgFQgDgCgEAAQgEAAgCACg");
	this.shape_6.setTransform(141.5,29.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGAlIgHgDIgFgEIgFgGIAHgEQADAFAEACQAFADAEAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIAAgGIAEgBIAFgCIADgEIABgFQAAgGgDgDQgEgDgGAAQgEAAgEACQgDADgCAEIgHgEQADgHAGgDQAGgDAGAAQAEAAAEABIAHAEQADACACAEQACADAAAFQAAAGgDAEQgEAEgEACIAEACIAEADIADAFIABAHQAAAFgCAEQgCAEgEADQgDADgFABIgIABIgGAAg");
	this.shape_7.setTransform(135.4,29.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLAkIAag/IgnAAIAAgIIAxAAIAAAGIgaBBg");
	this.shape_8.setTransform(129.7,29.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLAkIAag/IgnAAIAAgIIAxAAIAAAGIgaBBg");
	this.shape_9.setTransform(123.8,29.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAlIgHgDIgFgEIgFgGIAHgEQADAFAEACQAFADAEAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIAAgGIAEgBIAFgCIADgEIABgFQAAgGgDgDQgEgDgGAAQgEAAgEACQgDADgCAEIgHgEQADgHAGgDQAGgDAGAAQAEAAAEABIAHAEQADACACAEQACADAAAFQAAAGgDAEQgEAEgEACIAEACIAEADIADAFIABAHQAAAFgCAEQgCAEgEADQgDADgFABIgIABIgGAAg");
	this.shape_10.setTransform(117.8,29.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgLAiQgFgDgDgFQgDgFgCgHQgBgHAAgHIABgNQACgGADgGQADgFAFgDQAFgDAGAAQAHAAAFADQAFADADAFQADAGACAGIABANQAAAHgBAHQgCAHgDAFQgDAFgFADQgFADgHAAQgGAAgFgDgAgHgaIgFAHIgDAJIgBAKIABALQABAFACAEQACAFADACQADADAEAAQAEAAAEgDQADgCACgFIADgJIABgLIgBgKIgDgJQgCgEgDgDQgEgCgEAAQgEAAgDACg");
	this.shape_11.setTransform(112.2,29.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAGAkIAAg9IgPAKIgFgGIAVgOIAIAAIAABHg");
	this.shape_12.setTransform(105.7,29.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgbAEIAAgHIA2AAIAAAHg");
	this.shape_13.setTransform(98.6,30.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AASAlIAAgiIgkAAIAAAiIgIAAIAAhJIAIAAIAAAgIAkAAIAAggIAJAAIAABJg");
	this.shape_14.setTransform(90.3,29.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgXAlIAAhJIAXAAQAMAAAGAGQAGAGAAALQAAAKgHAFQgGAFgLAAIgOAAIAAAegAgOAAIAOAAQAGAAAEgDQAEgDAAgIQAAgHgEgEQgDgDgHAAIgOAAg");
	this.shape_15.setTransform(84,29.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgUAlIAAhJIApAAIAAAIIghAAIAABBg");
	this.shape_16.setTransform(78.6,29.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgNAjQgGgDgEgGQgEgFgBgHIgCgOQAAgGACgHQABgHAEgFQAEgGAGgDQAGgDAHAAQAIAAAGADQAGADAEAGQADAFACAHQACAHAAAGQAAAHgCAHQgCAHgDAFQgEAGgGADQgGADgIAAQgHAAgGgDgAgJgbQgEADgDAEQgCAEgBAGQgCAFAAAFIACALQABAGACAEQADAEAEADQAFACAEAAQAGAAADgCQAEgDAEgEQACgEABgGIABgLIgBgKQgBgGgCgEQgDgEgFgDQgDgCgGAAQgEAAgFACg");
	this.shape_17.setTransform(72.1,29.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgHAIIAEgCQABgBABAAQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQABADAAADIgBAEIgEAFIgEADIgFADg");
	this.shape_18.setTransform(65.1,33);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgLAiQgFgDgDgFQgDgFgCgHQgBgHAAgHIABgNQACgGADgGQADgFAFgDQAFgDAGAAQAHAAAFADQAFADADAFQADAGACAGIABANQAAAHgBAHQgCAHgDAFQgDAFgFADQgFADgHAAQgGAAgFgDgAgHgaIgFAHIgDAJIgBAKIABALQABAFACAEQACAFADACQADADAEAAQAEAAAEgDQADgCACgFIADgJIABgLIgBgKIgDgJQgCgEgDgDQgEgCgEAAQgEAAgDACg");
	this.shape_19.setTransform(61.3,29.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAGAkIAAg9IgQAKIgEgGIAVgOIAIAAIAABHg");
	this.shape_20.setTransform(54.8,29.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgEAFQgBgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQABAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBgBAAg");
	this.shape_21.setTransform(49.4,32.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AASAaIAAglIgRAlIgBAAIgRglIAAAlIgIAAIAAgzIAKAAIAPAlIAQglIAKAAIAAAzg");
	this.shape_22.setTransform(44.9,30.4);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgJAZQgFgCgDgEQgDgEgCgFIgCgKIACgJQACgFADgEQADgEAEgCQAFgCAFgBQAGABAEACQAFACADAEQADAEACAFIACAJQAAAFgCAFQgCAGgDADQgDAEgFACQgEACgGAAQgFAAgEgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEAAQgDAAgDABg");
	this.shape_23.setTransform(38.7,30.4);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AANAaIAAgsIgZAAIAAAsIgJAAIAAgzIArAAIAAAzg");
	this.shape_24.setTransform(32.9,30.4);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgHAIIAFgCQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgCgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQABADAAADIgBAEIgEAFIgEADIgFADg");
	this.shape_25.setTransform(199.2,22.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAGAkIAAg9IgPAKIgFgGIAVgOIAIAAIAABHg");
	this.shape_26.setTransform(194.7,19.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgEAFQgBgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQABAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBgBAAg");
	this.shape_27.setTransform(191.4,22.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AANAaIAAgsIgZAAIAAAsIgJAAIAAgzIAqAAIAAAzg");
	this.shape_28.setTransform(187.4,20.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgVAmIAAhJIAHgBIABAFQAEgDADgBIAHgCQAGABAEACQAEACACAEQADAEABAEIACAKQgBAHgCAEQgCAFgDAEQgDAEgFABQgFACgEAAQgHAAgEgBIAAAWgAgHgcIgGAEIAAAgIAEACIAFABQAEAAACgCIAGgDQADgDABgDQACgEAAgFIAAgIIgDgGQgCgDgDgCQgDgCgDAAIgHACg");
	this.shape_29.setTransform(181.9,21.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgJAZQgFgCgEgEQgCgEgCgFIgCgKIACgJQACgFACgEQADgEAFgCQAFgCAFgBQAGABAEACQAGACACAEQADAEACAFIACAJQgBAFgBAFQgCAGgDADQgCAEgGACQgEACgGAAQgFAAgEgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_30.setTransform(176,20.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AALAaIgPgXIgJAAIAAAXIgHAAIAAgzIAHgBIAAAXIAGAAIADgBIACgBIACgEIABgFIADgFIADgEIADgCIAFAAIAFAAIgBAHIgCAAQgDAAgCABQgCABgCAFIgEAHIgCADIATAbg");
	this.shape_31.setTransform(171,20.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgHAIIAEgCQABgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgCgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQACADAAADIgCAEIgDAFIgEADIgFADg");
	this.shape_32.setTransform(164.7,22.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgJAjQgEgCgDgEQgDgEgCgFIgBgLQAAgJADgHQACgIAFgGQAFgGAHgEQAGgEAIgBIACAHIgJADIgHAFQgEADgDAEQgCAEgCAEIAGgDIAGgBQAGAAAEACQAEACADADQADADABAEIABAKQAAAFgCAEQgBAEgDAEQgCADgFACQgEABgFAAQgFAAgFgCgAgGgBQgDABgEABIAAAIIAAAHIADAHIAEAFQADACAEAAQAEAAACgBIAEgEQACgCAAgDIABgGIgBgHIgCgFIgFgDQgCgBgEAAIgGABg");
	this.shape_33.setTransform(161,19.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAGAkIAAg9IgPAKIgFgGIAVgOIAIAAIAABHg");
	this.shape_34.setTransform(154.4,19.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgEAFQgBgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQABAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBgBAAg");
	this.shape_35.setTransform(151.1,22.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AAUAgIAAgMIgnAAIAAAMIgIAAIAAgTIADAAQADgCADgDQACgEABgEIABgJIABgJIAAgNIAjAAIAAAsIAGAAIAAATgAgFgPIAAAIIgBAHIgDAIIgEAFIAaAAIAAglIgSAAg");
	this.shape_36.setTransform(146.9,20.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgHAIIAFgCQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgCgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQABADAAADIgBAEIgEAFIgEADIgFADg");
	this.shape_37.setTransform(140.7,22.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AANAaIAAgSIgOAAQgBAGgCAEIgEAFIgEADIgDAAIgGAAIAAgHIADAAIACAAIADgBIACgEIACgHIgDgCIgEgDIgCgEIgBgGQAAgIAFgFQAGgEAJAAIAVAAIAAAzgAgHgQQgEADAAAFQAAAFADACQADACAFAAIANAAIAAgTIgNAAQgEAAgDACg");
	this.shape_38.setTransform(136.9,20.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgDAAgDQAAgHADgDQADgCAFgCQAEgDAFAAIALgCIAAgBQAAgGgDgDQgDgDgFAAQgDABgDABQgDABgCAEIgGgFQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEABgDAAIgHgBgAAEAAIgHABQgDACgCACQgCADAAAEIABAEIACACIADADIAEAAQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_39.setTransform(131.8,20.1);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AAMAaIgQgXIgIAAIAAAXIgJAAIAAgzIAJgBIAAAXIAGAAIACgBIACgBIABgEIACgFIADgFIADgEIAEgCIAEAAIAGAAIgBAHIgDAAQgDAAgCABQgCABgCAFIgDAHIgDADIAUAbg");
	this.shape_40.setTransform(127.3,20.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgGAaQgEgCgEgDQgDgDgCgFQgCgGAAgHQAAgGACgFQACgFADgEQAEgDAEgCQAEgCAEAAQAEABADABIAGAEIAEADIACAFIgGADQgCgFgEgCQgDgCgEgBIgFACIgFAEQgCACgCAEIgBAIIABAJQACAEACADIAFADQADACADAAQAEAAADgDQAEgCACgEIAGAEQgDAFgFADQgGADgGAAIgIgBg");
	this.shape_41.setTransform(121.9,20.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AANAaIAAgXIgZAAIAAAXIgIAAIAAgyIAIgCIAAAXIAZAAIAAgWIAJAAIAAAzg");
	this.shape_42.setTransform(116.4,20.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgDAAgDQAAgHADgDQADgCAFgCQAEgDAFAAIALgCIAAgBQAAgGgDgDQgDgDgFAAQgDABgDABQgDABgCAEIgGgFQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEABgDAAIgHgBgAAEAAIgHABQgDACgCACQgCADAAAEIABAEIACACIADADIAEAAQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_43.setTransform(110.8,20.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgHAbQgDgBgCgCIgFgDIgDgFIAHgEIACAEIADACIAEADIAFAAQAGAAADgCQADgDAAgEQAAgEgDgCQgCgCgEgBIgEAAIgEAAIAAgFIAEAAIADgBQAEgBADgCQACgCAAgEQAAgEgEgCQgDgCgEAAQgJAAgEAKIgGgCQACgIAFgDQAFgDAHgBQAJAAAFAFQAFADAAAHQAAAEgDAEQgDADgEABQAFAAADADQADADAAAFQAAAIgGAFQgFADgKAAIgHAAg");
	this.shape_44.setTransform(105.9,20.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AANAaIAAgSIgOAAQgBAGgCAEIgEAFIgEADIgDAAIgGAAIAAgHIADAAIACAAIADgBIACgEIACgHIgDgCIgEgDIgCgEIgBgGQAAgIAFgFQAGgEAJAAIAVAAIAAAzgAgHgQQgEADAAAFQAAAFADACQADACAFAAIANAAIAAgTIgNAAQgEAAgDACg");
	this.shape_45.setTransform(100.9,20.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgWAmIAAhJIAIgBIABAFQADgDAEgBIAHgCQAGABAEACQAEACADAEQACAEABAEIABAKQAAAHgCAEQgCAFgDAEQgDAEgFABQgFACgEAAQgHAAgEgBIAAAWgAgHgcIgGAEIAAAgIAEACIAFABQAEAAACgCIAHgDQACgDABgDQACgEAAgFIgBgIIgCgGQgCgDgDgCQgDgCgDAAIgHACg");
	this.shape_46.setTransform(95.8,21.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgJAZQgFgCgDgEQgDgEgCgFIgCgKIACgJQACgFADgEQADgEAEgCQAFgCAFgBQAGABAEACQAFACADAEQADAEACAFIACAJQAAAFgCAFQgCAGgDADQgDAEgFACQgEACgGAAQgFAAgEgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_47.setTransform(90,20.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgVAmIAAhJIAHgBIABAFQADgDAEgBIAHgCQAGABAEACQAEACACAEQADAEACAEIABAKQAAAHgCAEQgDAFgDAEQgEAEgEABQgFACgEAAQgHAAgEgBIAAAWgAgHgcIgGAEIAAAgIADACIAGABQAEAAADgCIAFgDQADgDACgDQABgEAAgFIAAgIIgDgGQgCgDgDgCQgDgCgDAAIgHACg");
	this.shape_48.setTransform(84.4,21.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgDAAgDQAAgHADgDQADgCAFgCQAEgDAFAAIALgCIAAgBQAAgGgDgDQgDgDgFAAQgDABgDABQgDABgCAEIgGgFQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEABgDAAIgHgBgAAEAAIgHABQgDACgCACQgCADAAAEIABAEIACACIADADIAEAAQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_49.setTransform(78.8,20.1);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgDAaIAAgsIgRAAIAAgHIApAAIgBAHIgQAAIAAAsg");
	this.shape_50.setTransform(74.3,20.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgHAkQgGgCgEgFQgEgEgDgHQgCgIAAgKQAAgJACgHQADgIAEgEQAEgFAGgCQAEgCAFAAQAIAAAHAEQAHAEADAHIgIAEIgCgEIgEgDIgEgDQgDgBgDAAQgJAAgFAIQgGAIAAANQAAAIACAFQABAGAEAEQACADAEACQAEACADAAIAGgBIAEgCIAFgEIACgEIAHAEIgDAGIgGAEQgCADgEABQgEABgFAAQgFAAgFgCg");
	this.shape_51.setTransform(69.3,19);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgEAFQgBgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQABAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBgBAAg");
	this.shape_52.setTransform(65,22.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAQAaIAAgsIgSAAIAAASIgCANQgCAGgDAEQgEADgHAAIgDAAIAAgHIACAAIADAAIACgBIACgCIACgFIABgFIAAgGIABgKIAAgPIAiAAIAAAzg");
	this.shape_53.setTransform(60.8,20.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgUAlIgDgCIABgGIAEABIAEAAIADgBIAEgFIADgKIgUgyIAKAAIAOAnIAPgnIAKAAIgaBBQgCAFgDACQgEABgEAAIgGAAg");
	this.shape_54.setTransform(55.9,21.2);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgHAIIAFgCQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgBgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQABADAAADIgBAEIgEAFIgEADIgFADg");
	this.shape_55.setTransform(50.1,22.6);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgDAAgDQAAgHADgDQADgCAFgCQAEgDAFAAIALgCIAAgBQAAgGgDgDQgDgDgFAAQgDABgDABQgDABgCAEIgGgFQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEABgDAAIgHgBgAAEAAIgHABQgDACgCACQgCADAAAEIABAEIACACIADADIAEAAQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_56.setTransform(46.5,20.1);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AAUAgIAAgMIgnAAIAAAMIgIAAIAAgTIADAAQAEgCABgDQADgEABgEIABgJIABgJIAAgNIAjAAIAAAsIAGAAIAAATgAgFgPIAAAIIgBAHIgDAIIgEAFIAaAAIAAglIgSAAg");
	this.shape_57.setTransform(41.1,20.7);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgJAZQgFgCgEgEQgDgEgBgFIgCgKIACgJQABgFADgEQADgEAFgCQAFgCAFgBQAGABAEACQAGACACAEQADAEACAFIACAJQgBAFgBAFQgCAGgDADQgCAEgGACQgEACgGAAQgFAAgEgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_58.setTransform(35.3,20.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgKAkQgFgDgDgDQgDgEgBgGIgBgNQAAgSAFgLQAGgJAMgBIAFAAIAFAAQACgCAAgDIAHACQgBAGgDADQgDABgHABIgFAAIgHACIgEAFIgDAGIgBAGQADgEAEgCQAEgCAGAAQAFAAAEACQAFACACAEQADADACAEQABAEAAAGQAAAFgBAEQgCAFgDAEQgDAEgFACQgEACgGAAQgGAAgEgCgAgGgFIgFAEIgDAGIgBAHIABAHIADAGQACADADACQADABADAAQAEAAADgBQADgCACgDIADgGIABgHIgBgHIgDgFQgCgDgDgCQgDgBgEAAQgDAAgDABg");
	this.shape_59.setTransform(29.5,19);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgKAZQgEgCgEgEQgDgEgBgFIgBgKIABgJQABgFADgEQADgEAFgCQAFgCAFgBQAGABAEACQAGACACAEQAEAEABAFIACAJQgBAFgBAFQgBAGgEADQgCAEgGACQgEACgGAAQgFAAgFgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_60.setTransform(23.7,20.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AAQAaIAAgsIgSAAIAAASIgCANQgCAGgDAEQgEADgHAAIgDAAIAAgHIACAAIADAAIACgBIACgCIACgFIABgFIAAgGIABgKIAAgPIAiAAIAAAzg");
	this.shape_61.setTransform(17.6,20.1);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgIAkQgFgCgFgFQgDgEgDgHQgCgIAAgKQAAgJACgHQADgIAEgEQAEgFAFgCQAFgCAFAAQAIAAAHAEQAHAEACAHIgHAEIgCgEIgEgDIgEgDQgDgBgDAAQgJAAgFAIQgGAIAAANQAAAIACAFQACAGADAEQACADAEACQAEACADAAIAGgBIAFgCIADgEIADgEIAHAEIgDAGIgGAEQgDADgDABQgEABgFAAQgFAAgGgCg");
	this.shape_62.setTransform(12.2,19);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AANAaIAAgSIgOAAQgBAGgCAEIgEAFIgEADIgDAAIgGAAIAAgHIADAAIACAAIADgBIACgEIACgHIgDgCIgEgDIgCgEIgBgGQAAgIAFgFQAGgEAJAAIAVAAIAAAzgAgHgQQgEADAAAFQAAAFADACQADACAFAAIANAAIAAgTIgNAAQgEAAgDACg");
	this.shape_63.setTransform(203.8,9.5);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgCAAgFQAAgFADgEQADgCAFgCQAEgDAFgBIALgBIAAgBQAAgGgDgDQgDgCgFAAQgDgBgDACQgDACgCACIgGgEQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEACgDgBIgHgBgAAEAAIgHABQgDABgCADQgCACAAAEIABAFIACACIADACIAEABQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_64.setTransform(198.7,9.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AAMAaIgQgYIgJAAIAAAYIgIAAIAAgzIAIgBIAAAXIAHAAIACgBIABgCIADgCIABgGIADgFIADgEIAEgCIAEAAIAFAAIAAAHIgDAAQgDAAgCABQgCACgCAEIgEAHIgCAEIATAag");
	this.shape_65.setTransform(194.2,9.5);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgGAaQgEgCgEgDQgDgDgCgGQgCgEAAgIQAAgGACgFQACgGADgDQAEgDAEgCQAEgCAEAAQAEABADABIAGAEIAEAEIACADIgGAFQgCgGgEgCQgDgDgEABIgFABIgFAEQgCADgCADIgBAIIABAJQACAEACADIAFADQADACADAAQAEAAADgDQAEgBACgGIAGAFQgDAGgFADQgGACgGAAQgDABgFgCg");
	this.shape_66.setTransform(188.8,9.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgUAaIAAgzIAWAAQAIAAAEADQAEADAAAHQAAAFgCADQgDADgDABIAEAAIADACIADAEIABAFQAAAIgFADQgFAEgHAAgAgLATIAOAAIADAAIADgBIACgDIABgEQAAgDgCgDQgDgCgFAAIgNAAgAgLgDIAMAAQAFAAACgCQACgDAAgDQAAgHgIAAIgNAAg");
	this.shape_67.setTransform(183.7,9.5);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AgKAaQgEgDgEgEQgDgEgBgFIgBgKIABgJQABgFADgEQADgEAFgCQAFgCAFgBQAGABAEACQAGADACAEQAEADABAFIABAJQAAAGgBAEQgBAFgEAEQgCAEgGADQgEABgGAAQgFAAgFgBgAgGgSIgFAFIgDAGIgBAHIABAIIADAHQACADADABQADACADAAQAEAAADgCQADgBACgDIADgHIABgIIgBgHIgDgGIgFgFQgDgCgEABQgDgBgDACg");
	this.shape_68.setTransform(178,9.5);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AAQAaIAAgsIgSAAIAAASIgCANQgCAGgDAEQgEADgHAAIgDAAIAAgHIACAAIADAAIACgBIACgCIACgFIABgFIAAgGIABgKIAAgPIAiAAIAAAzg");
	this.shape_69.setTransform(171.9,9.5);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AANAmIAAgjIgZAdIAAAGIgIAAIAAgzIAIgBIAAAkIAZgcIAAgHIAIAAIAAAzgAgEgXIgGgCQgCgCgCgEQgCgCAAgFIAHAAIACAFIACACIAEACIACAAIADAAIAEgCIACgCIACgFIAHAAQAAAFgCACQgCAEgCACIgGACIgGABIgFgBg");
	this.shape_70.setTransform(166.6,8.3);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgCAAgFQAAgFADgEQADgCAFgCQAEgDAFgBIALgBIAAgBQAAgGgDgDQgDgCgFAAQgDgBgDACQgDACgCACIgGgEQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEACgDgBIgHgBgAAEAAIgHABQgDABgCADQgCACAAAEIABAFIACACIADACIAEABQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_71.setTransform(161.1,9.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AANAaIgNgTIgMATIgJAAIASgaIgRgZIAJAAIALATIAMgTIAJAAIgQAZIARAag");
	this.shape_72.setTransform(156.5,9.5);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AANAaIAAgiIgZAcIAAAGIgIAAIAAgzIAIgBIAAAkIAZgcIAAgHIAIAAIAAAzg");
	this.shape_73.setTransform(151.5,9.5);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AAAAlIgWg4IAAA3IgJAAIAAhIIAKAAIAVA4IAWg4IAKAAIAABIIgIAAIAAg3IgYA4g");
	this.shape_74.setTransform(144.6,8.5);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgDAFQgCgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQABAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape_75.setTransform(137.4,11.6);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgGAaQgEgCgEgDQgDgDgCgGQgCgEAAgIQAAgGACgFQACgGADgDQAEgDAEgCQAEgCAEAAQAEABADABIAGAEIAEAEIACADIgGAFQgCgGgEgCQgDgDgEABIgFABIgFAEQgCADgCADIgBAIIABAJQACAEACADIAFADQADACADAAQAEAAADgDQAEgBACgGIAGAFQgDAGgFADQgGACgGAAQgDABgFgCg");
	this.shape_76.setTransform(133.9,9.5);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AgHAIIAEgCQABgBABAAQAAAAABgBQAAAAAAgBQAAAAAAgBIgCgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQACADAAADIgCAEIgDAFIgEADIgFADg");
	this.shape_77.setTransform(127.9,12.1);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AgNAjQgGgDgDgGQgFgFgBgHIgCgOQAAgGACgHQABgHAFgFQADgGAGgDQAGgDAHAAQAIAAAGADQAFADAFAGQADAFACAHQACAHAAAGQAAAHgCAHQgCAHgDAFQgFAGgFADQgGADgIAAQgHAAgGgDgAgJgbQgEADgDAEQgDAEAAAGQgCAFAAAFIACALQABAGACAEQADAEAEADQAEACAFAAQAFAAAEgCQAFgDACgEQADgEABgGIACgLIgCgKQgBgGgDgEQgCgEgFgDQgEgCgFAAQgFAAgEACg");
	this.shape_78.setTransform(123.5,8.5);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AAAAlIgXg4IAAA3IgIAAIAAhIIAKAAIAVA4IAVg4IALAAIAABIIgJAAIAAg3IgWA4g");
	this.shape_79.setTransform(115.9,8.5);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgHAIIAEgCQABgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgCgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQACADAAADIgCAEIgDAFIgEADIgFADg");
	this.shape_80.setTransform(108.5,12.1);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AgDAPIAQgPIgOgOIAIgIIAXAWIgZAXgAgdAPIASgPIgQgOIAJgIIAWAWIgYAXg");
	this.shape_81.setTransform(104.5,9.4);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AgHAaIAAgoIgQAAIAAgMIAwAAIgCAMIgQAAIAAAog");
	this.shape_82.setTransform(98.8,9.5);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AgYAmIAAhIIANgCIABAFIAFgEQADgCAEAAQAGAAAEACQAFADADADQACAEABAFQACAFAAAGIgCAJQgBAFgEAEQgDAEgGADQgFACgGAAIgEAAIgEgCIAAAWgAgFgYIgFAEIAAAZIAHABQADAAADgBIAEgEIADgEIABgGIAAgGIgDgFQgBgDgCgBQgCgBgDAAQgDAAgCABg");
	this.shape_83.setTransform(93.5,10.5);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AgLAaQgFgDgDgEQgEgEgBgFIgCgKQAAgEACgFQABgFAEgEQADgEAFgCQAFgDAGAAQAHAAAFADQAFACADAEQADAEACAFQACAFAAAEQAAAFgCAFQgCAFgDAEQgDAEgFADQgFACgHAAQgGAAgFgCgAgFgOIgEAEIgCAFIgBAFIABAGIACAFIAEAEQADABACAAQADAAACgBQADgBABgDIADgFIAAgGIAAgFIgDgFQgBgDgDgBQgCgBgDAAQgCAAgDABg");
	this.shape_84.setTransform(87.4,9.5);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AAKAaIAAgoIgTAAIAAAoIgOAAIAAg0IAvAAIAAA0g");
	this.shape_85.setTransform(81.3,9.5);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AAQAaIAAgcIgNAcIgEAAIgOgcIAAAcIgOAAIAAg0IAPAAIAPAgIAPggIAOAAIAAA0g");
	this.shape_86.setTransform(74.5,9.5);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AAOAlIAAgrIgbAgIAAALIgQAAIAAhJIAQAAIAAArIAbggIAAgLIAQAAIAABJg");
	this.shape_87.setTransform(67.1,8.5);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AgNAGIAAgLIAbAAIAAALg");
	this.shape_88.setTransform(61.5,9.2);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FFFFFF").s().p("AANAaIAAgoIgNAAIAAAGIAAAIIgBAEIAAAEIgBAEQgCAGgEAFQgEADgIAAIgGAAIAAgLIADAAIAEgBQADgCAAgDIABgCIAAgFIAAgEIAAgIIAAgQIAqAAIAAA0g");
	this.shape_89.setTransform(56.3,9.5);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AALAbIAAgcIgVAUIAAAIIgOAAIAAgyIAOgDIAAAdIAVgTIAAgJIAOAAIAAA0g");
	this.shape_90.setTransform(50.4,9.5);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FFFFFF").s().p("AARAgIAAgLIghAAIAAALIgNAAIAAgXIAEAAQAGgGADgIQACgJAAgLIAAgGIAnAAIAAAoIAFAAIAAAXgAgDgDQgDAHgDAFIAUAAIAAgdIgMAAQAAAJgCAIg");
	this.shape_91.setTransform(43.9,10.1);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AgRAjQgGgEgGgJIANgHQADAFADADQAEACAFAAIAFgBQADgBADgCIAEgGIABgJIgbAAIAAgMIAaAAQgBgJgEgFQgFgEgFAAQgFAAgFADQgEADgCAEIgMgHIAFgHIAGgFIAIgDQAEgBAGAAQAFAAAHACQAFACAEAFQAEAEADAIQACAHAAAJQAAAJgCAIQgDAHgDAFQgEAEgGADQgHACgGAAQgJAAgHgDg");
	this.shape_92.setTransform(37.4,8.5);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFFFFF").s().p("AgDAAIAWgWIAJAIIgPAOIARAPIgJAIgAgdAAIAXgWIAJAIIgPAOIAQAPIgIAIg");
	this.shape_93.setTransform(31,9.4);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AgOAjQgHgDgEgGQgEgFgCgHQgCgHAAgHQAAgGACgHQACgHAEgFQAEgGAHgDQAGgDAIAAQAJAAAGADQAGADAFAGQADAFACAHQADAHAAAGQAAAHgDAHQgCAHgDAFQgFAGgGADQgGADgJAAQgIAAgGgDgAgIgWQgDACgCAEIgEAIIgBAIIABAJIAEAJQACADADACQAEACAEAAQAEAAAEgCQAEgCACgDQACgEACgFIABgJIgBgIQgCgFgCgDIgGgGQgEgCgEAAQgEAAgEACg");
	this.shape_94.setTransform(22,8.5);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("AgOAjQgGgDgEgGQgFgFgCgHQgCgHAAgHQAAgGACgHQACgHAFgFQAEgGAGgDQAGgDAIAAQAJAAAFADQAHADAEAGQAFAFACAHQACAHAAAGQAAAHgCAHQgCAHgFAFQgEAGgHADQgFADgJAAQgIAAgGgDgAgIgWQgDACgCAEIgEAIIgBAIIABAJIAEAJQACADADACQAEACAEAAQAFAAADgCQADgCADgDQADgEAAgFIABgJIgBgIQAAgFgDgDIgGgGQgDgCgFAAQgEAAgEACg");
	this.shape_95.setTransform(14.3,8.5);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AgOAjQgHgDgEgGQgEgFgCgHQgCgHAAgHQAAgGACgHQACgHAEgFQAEgGAHgDQAGgDAIAAQAIAAAGADQAHADAFAGQADAFACAHQADAHAAAGQAAAHgDAHQgCAHgDAFQgFAGgHADQgGADgIAAQgIAAgGgDgAgHgWQgEACgCAEIgEAIIgBAIIABAJIAEAJQACADAEACQADACAEAAQAEAAAEgCQADgCADgDQADgEABgFIABgJIgBgIQgBgFgDgDIgGgGQgEgCgEAAQgEAAgDACg");
	this.shape_96.setTransform(6.6,8.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,209.4,37.5);


(lib.Символ15 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.QE65Q80R();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,300,189);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMTAxQgDgCAAgGQAAgFADgDQADgDAGAAQAFAAADADQADADAAAFQAAAGgDACQgDAEgFAAQgGAAgDgEgALPAvQgJgFgHgIIARgOQAEAHAGADQAFAEAHAAIAHgBIAFgDIADgEIABgGQAAgDgCgCIgFgEIgGgCIgIgDIgLgEIgJgEQgEgEgDgEQgCgFAAgIQAAgFACgGQADgFAEgEQAFgEAGgDQAGgCAIAAIALABIAJADIAHAFIAHAHIgQALQgGgJgMAAQgHAAgEACQgEAEAAAFQAAADACACQACACADACIAGACIAIAEIALADQAFACAEADQAFAEACAFQADAFAAAGQAAAHgDAFQgCAGgEAFQgFAEgGACQgHAEgIAAQgOAAgKgGgAJ5AwQgKgEgHgHQgHgHgDgKQgEgJAAgLQAAgLAEgJQAEgKAHgGQAHgIAKgEQAJgEALAAQAIABAGABQAHACAGAEQAFACAFAGIAIAKIgRAKQgEgIgHgEQgHgFgKAAQgHAAgGADQgGACgFAFQgEAFgDAFQgCAHAAAGQAAAHACAGQADAGAEAEQAFAFAGADQAGADAHAAQALAAAHgGQAHgFAEgJIASAJQgEAHgFAFQgEAFgGAFIgNAFQgHADgIAAQgLAAgKgFgAGLAwQgKgEgHgHQgHgHgEgKQgEgJAAgLQAAgKAEgJQAEgKAHgHQAHgHAKgFQAJgEALAAQALAAAJAEQAKAFAHAHQAHAHAEAKQAEAJAAAKQAAALgEAJQgEAKgHAHQgHAHgKAEQgJAFgLAAQgLAAgJgFgAGSgeQgGACgFAFQgEAFgDAFQgCAHAAAGQAAAHACAGQADAGAEAFQAFAEAGADQAGADAHAAQAHAAAGgDQAGgDAFgEQAEgFADgGQACgGAAgHQAAgGgCgHQgDgFgEgFQgFgFgGgCQgGgDgHAAQgHAAgGADgAB/AwQgJgEgHgHQgHgHgEgKQgEgJAAgLQAAgLAEgJQAEgKAIgGQAHgIAJgEQAKgEALAAQAHABAHABQAGACAGAEQAGACAFAGIAIAKIgRAKQgFgIgGgEQgHgFgKAAQgHAAgHADQgGACgEAFQgFAFgCAFQgDAHAAAGQAAAHADAGQACAGAFAEQAEAFAGADQAGADAHAAQALAAAHgGQAIgFAEgJIARAJQgDAHgFAFQgFAFgGAFIgNAFQgHADgHAAQgMAAgKgFgAjhAwQgKgEgHgHQgHgIgEgJQgEgKAAgKQAAgKAEgJQAEgKAHgHQAHgHAKgFQAJgEAMAAQAIAAAHACQAHACAGAEQAFADAFAFIAIALIgRAJQgEgIgIgEQgHgFgKAAQgHAAgHACQgGAEgEAEQgFAFgCAFQgDAHAAAGQAAAHADAGQACAGAFAFQAEAEAHADQAGADAHAAQAMAAAIgGQAHgGADgKIghAAIAAgSIA1AAIAAAHQAAAKgDAKQgEAJgGAHQgHAHgJAEQgJAFgMAAQgMAAgJgFgAmdAyQgHgCgFgFQgFgEgDgIQgDgGAAgJIAAhCIAUAAIAABDIABAHIAEAFQACADADACIAHABIAHgBIAGgFIAEgFIABgHIAAhDIATAAIAABCQAAAJgDAGQgCAIgFAEQgFAFgHACQgHADgIAAQgIAAgGgDgAn3AvQgKgFgHgIIASgOQADAHAGADQAGAEAHAAIAHgBIAEgDIAEgEIAAgGQAAgDgBgCIgFgEIgHgCIgIgDIgKgEIgJgEQgFgEgCgEQgDgFAAgIQAAgFADgGQACgFAFgEQAEgEAHgDQAGgCAHAAIALABIAJADIAIAFIAGAHIgPALQgHgJgMAAQgHAAgDACQgEAEAAAFQAAADACACQABACADACIAHACIAIAEIAKADQAFACAFADQAEAEADAFQACAFAAAGQAAAHgCAFQgCAGgFAFQgEAEgHACQgHAEgIAAQgOAAgJgGgAsWAvQgJgFgHgIIARgOQAEAHAGADQAFAEAHAAIAHgBIAFgDIADgEIABgGQAAgDgCgCIgFgEIgGgCIgIgDIgLgEIgJgEQgEgEgDgEQgCgFAAgIQAAgFACgGQADgFAEgEQAFgEAGgDQAGgCAIAAIALABIAJADIAHAFIAHAHIgQALQgGgJgMAAQgHAAgEACQgEAEAAAFQAAADACACQACACADACIAGACIAIAEIALADQAFACAEADQAFAEACAFQADAFAAAGQAAAHgDAFQgCAGgEAFQgFAEgGACQgHAEgIAAQgOAAgKgGgAI9AzIAAhlIATAAIAABlgAIdAzIguhHIAABHIgTAAIAAhlIAWAAIAsBFIAAhFIATAAIAABlgAFQAzIgQgfIgRAAIAAAfIgTAAIAAhlIAgAAQAJAAAIACQAHADAFAEQAEAGADAGQADAHAAAHQAAAJgFAIQgEAIgJAEIAVAlgAEvACIAMAAQAGABAEgCQAEgBACgDIADgFQACgEAAgEQAAgHgFgFQgFgEgLgBIgMAAgADkAzIAAhTIgcAAIAAgSIBKAAIAAASIgbAAIAABTgAAcAzIAAhlIA8AAIAAASIgpAAIAAAYIApAAIAAARIgpAAIAAAYIApAAIAAASgAgnAzIAAhlIATAAIAABTIAlAAIAAASgAhuAzIAAhlIA8AAIAAASIgpAAIAAAYIApAAIAAARIgpAAIAAAYIApAAIAAASgAkeAzIgthHIAABHIgTAAIAAhlIAVAAIAsBFIAAhFIATAAIAABlgAohAzIAAhGIgfAoIgfgoIAABGIgTAAIAAhlIATAAIAfArIAggrIASAAIAABlgAqOAzIgGgSIgnAAIgHASIgUAAIAlhlIATAAIAkBlgAq1AOIAbAAIgOglgAMXAXIgCgNIgBgOIgBgPIgBgPIAAgQIATAAIAAAQIAAAPIgBAPIgBAOIgCANg");
	this.shape.setTransform(80.7,5.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,161.5,10.5);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFCC00").s().p("AJzBbQgQgFgMgMQgNgKgIgPQgIgOgDgSIgXAAIAABOIgjAAIAAi9IAjAAIAABOIAXAAQADgSAIgOQAIgPANgKQAMgLAQgGQAQgGARgBQAUABARAHQASAIAMANQANANAIASQAHASAAATQAAAVgHARQgIASgMAOQgNANgRAHQgSAIgUAAQgSgBgPgGgAJ9g5QgLAFgIAJQgIAHgEAMQgFAMAAAMQAAANAFAMQAEAMAIAIQAIAIALAFQALAFAMAAQANAAALgFQALgFAIgIQAIgIAEgMQAFgMAAgNQAAgMgFgMQgEgLgIgIQgIgJgLgFQgLgEgNAAQgMAAgLAEgAliBdQgMgFgIgHQgIgJgFgLQgEgMAAgNIAAhFQAAgNAFgMQAFgMAIgIQAJgJAMgEQALgGAPAAQAPAAALAGQAMAEAJAJQAIAIAFAMQAEAMAAANIAABFQAAAOgEALQgFALgIAJQgIAIgMAEQgMAFgPAAQgQAAgMgFgAlcg1QgHAJAAAMIAABCQAAAMAHAJQAHAHAOABQAPAAAHgJQAIgIAAgLIAAhDQAAgOgIgHQgHgJgOABQgOAAgIAIgAnwBeQgKgCgIgGQgIgFgGgGQgGgHgEgHIAhgTQAEAJAIAHQAIAHAMAAQAGAAAFgCQAGgDAEgDQAEgEACgGQACgFAAgHQAAgNgIgJQgIgKgOAAQgLABgHAFQgHAGgFAIIgggQIAOhlIBqAAIAAAhIhOAAIgFArQAFgEAIgDQAHgCAJAAQANAAALADQALAFAJAIQAIAIAFALQAFALAAAQQAAAOgFAMQgFALgIAJQgJAHgMAFQgMAFgOAAQgMAAgLgEgAHDBfIAAiEIhOCEIglAAIAAi9IAjAAIAACCIBMiCIAoAAIAAC9gADoBfIAAibIgzAAIAAgiICJAAIAAAiIgzAAIAACbgAA1BfIAAi9IBwAAIAAAiIhNAAIAAAsIBNAAIAAAhIhNAAIAAAsIBNAAIAAAigAABBfIgviKIgwCKIglAAIBDi9IAkAAIBCC9gAqMBfIg2hOIgMAAIAABOIgkAAIAAi9IAkAAIAABOIALAAIA3hOIAoAAIhCBdIBFBggAjwAsIAAgeIBgAAIAAAeg");
	this.shape.setTransform(75.5,9.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,151,19.5);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIA0QgDgDAAgGQAAgFADgEQADgDAFAAQAGAAADADQADAEAAAFQAAAGgDADQgEAEgFAAQgFAAgDgEgAgFAYIgBgOIgCgPIgBgQIAAgQIAAgSIATAAIAAASIAAAQIgBAQIgCAPIgCAOg");
	this.shape.setTransform(95.3,36.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRArQgIgEgHgFQgFgGgFgJQgDgIAAgLQAAgKADgIQAFgJAFgGQAGgGAJgDQAHgDAJAAQAHAAAHADQAIAEAFAFIAAgKIAUAAIAABXIgUAAIAAgMQgFAHgIADQgHAEgIAAQgIAAgHgDgAgJgYQgFACgDADQgEAEgCAFQgCAFAAAFQAAAFACAFQACAFAEAEQADAEAFACQAFACAFAAQAFAAAFgCQAFgCADgEIAGgJQABgFABgFQgBgFgBgFIgGgIQgDgEgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_1.setTransform(88.6,37.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgtBBIAAh/IAUAAIAAALQAFgGAHgEQAIgDAIAAQAIAAAIADQAIADAGAGQAGAGADAJQAEAHAAAMQAAALgEAHQgEAIgGAHQgGAFgIAEQgHADgIAAQgIgBgIgDQgHgDgFgGIAAAzgAgKgsQgFACgDAFQgEADgCAFQgCAFAAAGQAAAFACAFQACAFAEADQADADAFADQAFACAFAAQAFAAAFgCQAFgDADgDQAEgDACgFQACgFAAgFQAAgHgCgEQgCgFgEgEQgDgDgFgDQgFgBgFAAQgFAAgFABg");
	this.shape_2.setTransform(78.9,39.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRAqQgIgEgGgGQgGgGgEgIQgEgJAAgJQAAgJAEgIQAEgIAGgGQAGgHAIgDQAJgEAIAAQAKAAAHAEQAJADAGAHQAGAGAEAIQAEAIAAAJQAAAJgEAJQgEAIgGAGQgGAGgJAEQgHAEgKAAQgIAAgJgEgAgJgYQgFACgEAEQgDAEgBAFQgCAEAAAFQAAAFACAFQABAFADAEQAEADAFACQAFACAEAAQAFAAAFgCQAEgCAEgDQADgEACgFQACgFAAgFQAAgFgCgEQgCgFgDgEQgEgEgEgCQgFgCgFAAQgEAAgFACg");
	this.shape_3.setTransform(68.9,37.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUAqQgJgEgHgIIAOgNQAFAFAGADQAGACAGAAQAHAAAFgDQAEgCAAgFQAAgEgEgDQgFgCgIAAIgMAAIAAgQIAMAAQAHAAAEgDQAEgCAAgFQAAgEgEgCQgDgDgIAAQgFAAgGADQgFACgEAFIgPgMQAHgIAJgEQAJgEALAAQAHAAAHACQAGACAFADQAEADADAFQACAFAAAFQAAAHgDAFQgDAEgFADQAGACAEAFQADAFAAAIQAAAFgCAFQgDAFgEAEQgFADgHACQgHADgIAAQgMAAgJgEg");
	this.shape_4.setTransform(60,37.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAUAsIAAg5IgnA5IgUAAIAAhXIAUAAIAAA4IAmg4IAVAAIAABXg");
	this.shape_5.setTransform(51.5,37.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgkAsIAAhXIAnAAQAOAAAJAGQAIAGAAAMQABAMgLAGQANAFAAAOQAAANgJAGQgIAHgQAAgAgRAbIAVAAQAGAAAEgDQADgCgBgFQABgFgDgCQgEgDgGAAIgVAAgAgRgJIAVAAQAFAAACgCQAEgCAAgFQAAgEgEgCQgCgCgFAAIgVAAg");
	this.shape_6.setTransform(42.9,37.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgRAqQgJgEgFgGQgHgGgDgIQgEgIAAgKQAAgIAEgJQAEgIAGgGQAGgHAIgDQAJgEAIAAQAKAAAIAEQAJADAFAGQAGAGAEAIQAEAJAAAJIAAAHIhHAAQACAJAHAGQAHAGAKAAQAJAAAFgEQAHgFADgHIARAKQgGALgKAGQgLAHgOAAQgJAAgJgEgAgPgWQgHAFgCAIIAwAAQgCgJgGgEQgHgFgJAAQgIAAgHAFg");
	this.shape_7.setTransform(33.8,37.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAYAsIgYg8IgXA8IgVAAIAkhXIARAAIAkBXg");
	this.shape_8.setTransform(24.3,37.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgRAqQgJgEgFgGQgHgGgDgIQgEgIAAgKQAAgIAEgJQADgIAHgGQAGgHAIgDQAJgEAIAAQAKAAAIAEQAJADAGAGQAFAGAEAIQADAJAAAJIAAAHIhGAAQACAJAHAGQAHAGAKAAQAJAAAFgEQAHgFADgHIARAKQgGALgKAGQgLAHgOAAQgJAAgJgEgAgPgWQgGAFgDAIIAwAAQgCgJgGgEQgGgFgKAAQgIAAgHAFg");
	this.shape_9.setTransform(14.8,37.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgJAsIAAhEIgcAAIAAgTIBLAAIAAATIgcAAIAABEg");
	this.shape_10.setTransform(6,37.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAUAsIAAg5IgnA5IgUAAIAAhXIAUAAIAAA4IAmg4IAVAAIAABXg");
	this.shape_11.setTransform(187.9,18.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJAsIAAhEIgcAAIAAgTIBLAAIAAATIgcAAIAABEg");
	this.shape_12.setTransform(179.4,18.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgPAqQgIgEgHgGQgGgGgDgIQgEgJAAgJQAAgJAEgIQADgIAGgGQAHgHAIgDQAIgEAJAAQAHAAAHACQAGACAGAEQAFADAEAFQAEAFADAGIgSAIQgDgHgHgEQgGgFgIAAQgFAAgEACQgFACgEAEQgDAEgCAFQgCAEAAAFQAAAFACAFQACAFADAEQAEADAFACQAEACAFAAQAJAAAGgEQAGgFADgHIASAIQgDAGgEAFQgEAFgFAEIgMAGQgGACgIAAQgJAAgIgEg");
	this.shape_13.setTransform(170.9,18.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgRAqQgIgEgGgGQgHgGgDgIQgDgJgBgJQABgJADgIQADgIAHgGQAGgHAIgDQAIgEAJAAQAJAAAIAEQAJADAGAHQAHAGADAIQAEAIgBAJQABAJgEAJQgDAIgHAGQgGAGgJAEQgIAEgJAAQgJAAgIgEgAgJgYQgFACgEAEQgCAEgCAFQgCAEgBAFQABAFACAFQACAFACAEQAEADAFACQAEACAFAAQAGAAAEgCQAFgCADgDQAEgEACgFQABgFAAgFQAAgFgBgEQgCgFgEgEQgDgEgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_14.setTransform(161.4,18.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAcAsIAAg5IgcAfIgbgeIAAA4IgUAAIAAhXIATAAIAcAjIAegjIASAAIAABXg");
	this.shape_15.setTransform(151.2,18.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAUAsIAAg5IgnA5IgUAAIAAhXIAUAAIAAA4IAmg4IAVAAIAABXg");
	this.shape_16.setTransform(141.3,18.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgRAqQgIgEgGgGQgGgGgEgIQgEgJAAgJQAAgJAEgIQAEgIAGgGQAGgHAIgDQAJgEAIAAQAKAAAHAEQAJADAGAHQAGAGAEAIQAEAIAAAJQAAAJgEAJQgEAIgGAGQgGAGgJAEQgHAEgKAAQgIAAgJgEgAgJgYQgFACgEAEQgDAEgBAFQgCAEAAAFQAAAFACAFQABAFADAEQAEADAFACQAFACAEAAQAFAAAFgCQAEgCAEgDQADgEACgFQACgFAAgFQAAgFgCgEQgCgFgDgEQgEgEgEgCQgFgCgFAAQgEAAgFACg");
	this.shape_17.setTransform(131.9,18.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgJAsIAAhEIgcAAIAAgTIBLAAIAAATIgcAAIAABEg");
	this.shape_18.setTransform(123.1,18.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgPAqQgIgEgHgGQgGgGgDgIQgEgJAAgJQAAgJAEgIQADgIAGgGQAHgHAIgDQAIgEAJAAQAHAAAHACQAGACAGAEQAFADAEAFQAEAFADAGIgSAIQgDgHgHgEQgGgFgIAAQgFAAgEACQgFACgEAEQgDAEgCAFQgCAEAAAFQAAAFACAFQACAFADAEQAEADAFACQAEACAFAAQAJAAAGgEQAGgFADgHIASAIQgDAGgEAFQgEAFgFAEIgMAGQgGACgIAAQgJAAgIgEg");
	this.shape_19.setTransform(114.5,18.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgJAsIAAhEIgcAAIAAgTIBLAAIAAATIgcAAIAABEg");
	this.shape_20.setTransform(102.2,18.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRAqQgIgEgGgGQgHgGgDgIQgDgJgBgJQABgJADgIQADgIAHgGQAGgHAIgDQAIgEAJAAQAJAAAIAEQAJADAGAHQAHAGADAIQAEAIgBAJQABAJgEAJQgDAIgHAGQgGAGgJAEQgIAEgJAAQgJAAgIgEgAgJgYQgFACgEAEQgCAEgCAFQgCAEgBAFQABAFACAFQACAFACAEQAEADAFACQAEACAFAAQAGAAAEgCQAFgCADgDQAEgEACgFQABgFAAgFQAAgFgBgEQgCgFgEgEQgDgEgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_21.setTransform(93.4,18.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFCC00").s().p("AAfBQQgHgEgFgFQgFgFgEgHQgDgIAAgIQAAgIADgHQAEgHAFgFQAFgGAHgDQAIgDAIAAQAIAAAHADQAHADAFAGQAGAFADAHQADAHAAAIQAAAIgDAIQgDAHgGAFQgFAFgHAEQgHADgIAAQgIAAgIgDgAAlAhQgFAFAAAFQAAAGAFAEQAEAFAGAAQAFAAAFgFQAEgEAAgGQAAgFgEgFQgFgEgFAAQgGAAgEAEgAhXBQICJifIAmAAIiJCfgAg9gGQgHgDgFgGQgGgFgDgHQgDgHAAgIQAAgJADgHQADgHAGgFQAFgFAHgDQAHgEAJAAQAIAAAHAEQAHADAFAFQAFAFAEAHQADAHAAAJQAAAIgDAHQgEAHgFAFQgFAGgHADQgHADgIAAQgJAAgHgDgAg4g0QgEAEAAAGQAAAGAEAEQAFAEAGAAQAFAAAEgEQAFgEAAgGQAAgGgFgEQgEgFgFAAQgGAAgFAFg");
	this.shape_22.setTransform(75.1,14.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFCC00").s().p("AgWBPQgKgEgIgHQgGgHgEgKQgDgJAAgLIAAg7QAAgLAEgKQADgJAIgIQAHgHAKgEQAKgFALAAQAMAAAKAFQALAEAHAHQAHAIAEAJQAEAKAAALIAAA7QAAAMgEAJQgEAJgHAHQgHAHgKAEQgKAEgNAAQgMAAgKgEgAgRgtQgGAIAAAKIAAA4QgBAKAHAIQAGAGALAAQAMAAAHgHQAGgHAAgJIAAg5QAAgLgGgHQgHgHgLAAQgLAAgHAHg");
	this.shape_23.setTransform(59.5,14.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFCC00").s().p("AgSBPQgJgDgHgEQgHgEgFgGQgFgFgDgGIAcgQQAEAHAGAGQAHAGAJAAQAFAAAFgCQAEgCAEgDQADgDACgFQACgFAAgFQAAgMgHgHQgGgIgMAAQgJAAgGAFQgGAEgEAHIgbgNIALhVIBZAAIAAAcIhAAAIgGAjIAMgFQAGgCAHAAQAKAAAKADQAKAEAGAHQAIAGADAJQAFAKAAAOQAAALgEAKQgEAKgIAHQgHAHgKAEQgKADgMAAQgJAAgJgCg");
	this.shape_24.setTransform(47.1,15);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFCC00").s().p("AgfBMQgPgGgLgMQgLgLgHgPQgGgPAAgRQAAgQAGgPQAHgPALgLQALgMAPgGQAOgHARAAQARAAAPAHQAPAGALAMQAMALAGAPQAGAPAAAQQAAARgGAPQgGAPgMALQgLAMgPAGQgPAHgRAAQgRAAgOgHgAgTgwQgLAEgGAHQgIAIgDAJQgFAKAAAKQAAALAFAKQADAJAIAIQAGAHALAEQAJAEAKAAQALAAAJgEQAKgEAHgHQAHgIAEgJQAFgKAAgLQAAgKgFgKQgEgJgHgIQgHgHgKgEQgJgEgLAAQgKAAgJAEg");
	this.shape_25.setTransform(27.1,14.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFCC00").s().p("AA0BfIAAgeIhmAAIAAAeIgdAAIAAg6IARAAIAwiDIAeAAIAvCDIAQAAIAAA6gAgfAlIBAAAIghhbg");
	this.shape_26.setTransform(10.2,16.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,194.7,47.9);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVA8IATgrIglhMIAJAAIAfBDIAehDIAJAAIg1B3g");
	this.shape.setTransform(183.1,34.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAXApIgiglIgNAAIAAAlIgIAAIAAhRIAIAAIAAAlIAMAAIAiglIAKAAIglAoIAmApg");
	this.shape_1.setTransform(174.9,32.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcApIAAhJIg3AAIAABJIgHAAIAAhRIBFAAIAABRg");
	this.shape_2.setTransform(165.6,32.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgVA8IATgrIglhMIAJAAIAfBDIAehDIAJAAIg1B3g");
	this.shape_3.setTransform(156.3,34.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAXApIgjglIgMAAIAAAlIgIAAIAAhRIAIAAIAAAlIAMAAIAiglIAJAAIgkAoIAmApg");
	this.shape_4.setTransform(148.1,32.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQAoQgIgEgGgFQgFgHgDgHQgDgIAAgJQAAgIADgHQADgJAFgFQAGgGAIgEQAIgCAIAAQAJAAAHACQAIAEAGAGQAGAFADAJQADAHAAAIQAAAJgDAIQgDAHgGAHQgGAFgIAEQgHACgJAAQgIAAgIgCgAgMgfQgHADgEAEQgFAFgDAHQgCAGAAAGQAAAHACAHQADAGAFAFQAEAFAHADQAFACAHAAQAHAAAHgCQAFgDAFgFQAFgFADgGQACgHAAgHQAAgGgCgGQgDgHgFgFQgFgEgFgDQgHgDgHAAQgHAAgFADg");
	this.shape_5.setTransform(138.5,32.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAbApIAAhJIg1AAIAABJIgJAAIAAhRIBHAAIAABRg");
	this.shape_6.setTransform(128.7,32.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEAoQgGgDgGgFQgGgGgDgHQgEgHAAgIIgPAAIAAAlIgIAAIAAhRIAIAAIAAAlIAPAAQABgIADgHQADgHAGgFQAGgFAGgEQAHgCAIAAQAJAAAIACQAHAEAFAGQAGAFADAJQAEAHAAAIQAAAJgEAIQgDAHgGAHQgFAFgHAEQgIACgJAAQgIAAgHgCgAgBgfQgGADgEAEQgFAFgCAHQgDAGAAAGQAAAHADAHQACAGAFAFQAEAFAGADQAFACAHAAQAHAAAHgCQAFgDAFgFQAEgFADgGQADgHAAgHQAAgGgDgGQgDgHgEgFQgFgEgFgDQgHgDgHAAQgHAAgFADg");
	this.shape_7.setTransform(114.3,32.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVA8IATgrIglhMIAJAAIAfBDIAehDIAJAAIg1B3g");
	this.shape_8.setTransform(103.2,34.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AA0AyIAAgSIhuAAIAAhRIAIAAIAABKIAqAAIAAhKIAIAAIAABKIApAAIAAhKIAIAAIAABKIAKAAIAAAZg");
	this.shape_9.setTransform(92.5,33.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgEAoQgGgDgGgFQgGgGgDgHQgDgHgBgIIgOAAIAAAlIgIAAIAAhRIAIAAIAAAlIAOAAQABgIADgHQADgHAGgFQAGgFAGgEQAHgCAIAAQAJAAAIACQAHAEAFAGQAGAFADAJQADAHAAAIQAAAJgDAIQgDAHgGAHQgFAFgHAEQgIACgJAAQgIAAgHgCgAgBgfQgGADgFAEQgEAFgDAHQgCAGAAAGQAAAHACAHQADAGAEAFQAFAFAGADQAFACAHAAQAIAAAFgCQAHgDAEgFQAEgFACgGQADgHABgHQgBgGgDgGQgCgHgEgFQgEgEgHgDQgFgDgIAAQgHAAgFADg");
	this.shape_10.setTransform(79.3,32.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8IATgrIglhMIAJAAIAfBDIAehDIAJAAIg1B3g");
	this.shape_11.setTransform(68.3,34.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAlAyIAAgSIhJAAIAAASIgIAAIAAgZIAHAAIAihKIAIAAIAhBKIAGAAIAAAZgAgcAZIA5AAIgdhBg");
	this.shape_12.setTransform(59.1,33.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgQAoQgIgEgFgFQgHgHgCgHQgDgIAAgJQAAgHADgIQADgJAGgFQAGgGAHgEQAIgCAIAAQAKAAAHACQAHADAGAGQAGAGADAHQADAIAAAJIAAADIhMAAQABAHACAGQADAGAFAEQAFAEAGADQAGACAHAAQALAAAIgFQAJgGAEgKIAHADQgGAMgJAHQgJAGgPAAQgJAAgIgCgAgLggQgHACgEAEQgEAFgDAFQgEAGAAAHIBDAAQgBgIgDgFQgCgFgEgFQgFgEgGgCQgFgDgIAAQgGAAgFADg");
	this.shape_13.setTransform(49.5,32.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAgApIgghHIgfBHIgJAAIAlhRIAHAAIAlBRg");
	this.shape_14.setTransform(39.9,32.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgOAoQgIgEgGgGQgFgFgEgJQgDgHAAgJQAAgIADgIQAEgIAFgFQAGgGAIgEQAIgCAIAAQAGAAAGABQAGACAGADQAFAEADAEQAEAFADAFIgIAEQgEgKgIgGQgIgFgLAAQgHAAgGADQgGADgFAEQgFAFgCAHQgDAGAAAGQAAAHADAHQACAGAFAFQAFAFAGADQAHACAGAAQALABAIgHQAIgGAEgJIAIADQgCAFgEAFQgEAFgFADQgFAEgGACQgGACgHgBQgIAAgIgCg");
	this.shape_15.setTransform(30.5,32.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQAoQgHgEgGgGQgGgFgDgJQgDgHAAgJQAAgIADgHQADgIAGgGQAGgGAHgEQAIgCAIAAIAKABQAFABAFADIAIAGQAEAEADAFIAAgTIAHAAIAABRIgHAAIAAgSIgHAIQgEAEgEADIgKADIgKABQgIAAgIgCgAgMgfQgGADgFAEQgFAFgDAHQgCAGAAAGQAAAHACAHQADAGAFAFQAFAFAGADQAGACAGAAQAIAAAGgCQAGgDAFgFQAFgFADgGQACgHAAgHQAAgGgCgGQgDgHgFgFQgFgEgGgDQgGgDgIAAQgGAAgGADg");
	this.shape_16.setTransform(16.6,32.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAcApIAAglIg3AAIAAAlIgIAAIAAhRIAIAAIAAAlIA3AAIAAglIAIAAIAABRg");
	this.shape_17.setTransform(6.8,32.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgMA4IAAhXIgjAAIAAgYIBfAAIAAAYIgjAAIAABXg");
	this.shape_18.setTransform(184.8,14.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgXA2QgJgEgIgIQgIgHgFgLQgEgKAAgOQAAgNAEgKQAFgMAIgGQAIgIAJgEQAKgEALAAQAKAAAJAEQAJAEAHAIIAAgOIAZAAIAABvIgZAAIAAgPQgHAIgJAFQgKAEgJAAQgKAAgLgEgAgLgfQgHADgEAFQgFAEgCAGQgDAGAAAHQAAAHADAGQACAGAFAFQAEAFAHACQAFADAHAAQAHAAAGgDQAGgCAFgFQAEgFACgGQADgGAAgHQAAgGgDgHQgCgGgEgEQgFgFgGgDQgGgDgHABQgHgBgFADg");
	this.shape_19.setTransform(173.2,14.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAVA4IglgsIgKAAIAAAsIgZAAIAAhvIAZAAIAAAsIAIAAIAmgsIAeAAIgwA2IAzA5g");
	this.shape_20.setTransform(161.8,14.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAZA4IAAhJIgxBJIgZAAIAAhvIAYAAIAABHIAxhHIAbAAIAABvg");
	this.shape_21.setTransform(150,14.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgMBhIAAgwQgMABgKgFQgLgEgIgIQgIgIgFgKQgEgKAAgLQAAgLAEgLQAFgKAIgHQAIgIALgFQAKgEAMAAIAAgiIAZAAIAAAiQAMAAALAEQALAFAIAIQAHAHAFAKQAEALAAALQAAALgEAKQgFAKgIAIQgIAIgKAEQgLAFgMgBIAAAwgAANAbQAHgBAGgDQAGgDAFgDQAEgFACgGQADgGAAgGQAAgHgDgGQgCgGgEgEQgFgEgGgDQgGgDgHgBgAgZgkQgGACgEAEQgFAFgCAGQgDAGAAAHQAAAGADAGQACAGAFAFQAEADAGADQAHADAGABIAAhDQgGABgHADg");
	this.shape_22.setTransform(136.8,15.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAZA4IAAhJIgxBJIgZAAIAAhvIAZAAIAABHIAwhHIAaAAIAABvg");
	this.shape_23.setTransform(123.7,14.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgMA4IAAhXIgjAAIAAgYIBfAAIAAAYIgjAAIAABXg");
	this.shape_24.setTransform(112.8,14.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag5BSIAAihIAaAAIAAAPQAFgIAKgFQAJgEALAAQAKAAAKAEQAKAEAHAHQAIAHAEALQAFALAAAOQAAANgFAKQgFALgHAHQgHAIgLAEQgKAEgJAAQgLAAgJgEQgKgEgFgIIAABAgAgNg3QgGADgEAEQgFAFgCAGQgDAGABAHQgBAIADAGQACAGAFAEQAEAFAGACQAHADAGAAQAGAAAHgDQAFgCAFgFQAFgEADgGQACgGAAgIQAAgHgCgGQgDgGgFgFQgFgEgFgDQgHgDgGAAQgGAAgHADg");
	this.shape_25.setTransform(101.7,16.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgWA2QgLgFgIgIQgHgIgFgKQgDgLAAgMQgBgLAFgLQAEgKAIgIQAIgIAKgEQALgFALAAQAMAAALAFQAKADAIAIQAIAIAEAKQAFALgBAMIAAAJIhZAAQACAMAKAHQAIAHANAAQALAAAIgFQAIgFAEgKIAVANQgHAOgNAHQgNAJgTAAQgMAAgLgEgAgTgcQgIAGgEAKIA+AAQgDgLgIgGQgIgFgMAAQgKgBgJAHg");
	this.shape_26.setTransform(89.1,14.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgUA1QgKgFgIgHQgIgIgEgLQgFgKABgMQgBgLAFgLQAEgKAIgIQAIgIAKgEQALgFALAAQAJAAAJACQAIADAHAFQAHAEAFAGQAFAHADAHIgXAKQgDgJgJgGQgIgFgJAAQgHAAgGADQgFADgFAEQgEAFgDAGQgDAGAAAGQAAAHADAGQADAGAEAFQAFAEAFADQAGACAHAAQAKABAIgGQAHgGAEgJIAYAKQgEAHgFAHQgFAHgHAEQgGAFgJACQgIADgKAAQgLAAgLgFg");
	this.shape_27.setTransform(77.2,14.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAjA4IAAhIIgjAnIgignIAABIIgZAAIAAhvIAYAAIAjAsIAlgsIAXAAIAABvg");
	this.shape_28.setTransform(59.8,14.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAZA4IAAhJIgxBJIgaAAIAAhvIAZAAIAABHIAxhHIAbAAIAABvg");
	this.shape_29.setTransform(47.3,14.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag5BSIAAihIAZAAIAAAPQAHgIAJgFQAJgEAKAAQALAAAKAEQAKAEAHAHQAIAHAFALQAEALAAAOQAAANgEAKQgGALgHAHQgIAIgKAEQgJAEgLAAQgKAAgJgEQgJgEgHgIIAABAgAgNg3QgGADgFAEQgDAFgDAGQgCAGgBAHQABAIACAGQADAGADAEQAFAFAGACQAGADAHAAQAGAAAGgDQAHgCAEgFQAFgEACgGQADgGAAgIQAAgHgDgGQgCgGgFgFQgEgEgHgDQgGgDgGAAQgHAAgGADg");
	this.shape_30.setTransform(35.4,16.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgWA2QgKgEgIgIQgHgHgGgLQgEgKAAgOQAAgNAEgKQAFgMAIgGQAIgIAKgEQAJgEALAAQAKAAAJAEQAJAEAHAIIAAgOIAZAAIAABvIgZAAIAAgPQgHAIgJAFQgJAEgKAAQgLAAgJgEgAgLgfQgGADgFAFQgFAEgCAGQgDAGAAAHQAAAHADAGQACAGAFAFQAFAFAGACQAFADAGAAQAIAAAGgDQAGgCAEgFQAFgFADgGQACgGAAgHQAAgGgCgHQgDgGgFgEQgEgFgGgDQgGgDgIABQgGgBgFADg");
	this.shape_31.setTransform(22.3,14.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAsBSIAAgaIhYAAIAAAaIgYAAIAAgyIAOAAIAphxIAaAAIAqBxIAOAAIAAAygAgbAgIA3AAIgchPg");
	this.shape_32.setTransform(9.1,14.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,200,42.9);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgDAhIAAgcIgdAAIAAgIIAdAAIAAgdIAIAAIAAAdIAcAAIAAAIIgcAAIAAAcg");
	this.shape.setTransform(17.5,12.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRA/QgJgDgGgHQgGgGgEgIQgDgIAAgKQAAgJADgIQADgHAEgGIAng5IANAAIgfAtQAHgDAJAAQAJAAAIAEQAIADAGAGQAGAHAEAHQADAIAAAKQAAAKgDAIQgEAIgGAGQgGAHgJADQgIAEgKAAQgJAAgIgEgAgNgMQgHADgEAFQgFAEgDAHQgDAGAAAIQAAAHADAHQADAHAFAEQAEAFAHADQAHADAGAAQAIAAAGgDQAHgDAFgFQAEgEADgHQADgHAAgHQAAgIgDgGQgDgHgEgEQgFgFgHgDQgGgCgIAAQgGAAgHACg");
	this.shape_1.setTransform(7.5,12.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,24,26.3);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAZApIAAgeIgZAAIgCAAIgCAAIgTAeIgJAAIAUgfQgGgCgDgCQgEgDgCgDIgDgHIgBgHQAAgGACgEQABgFAFgEQAEgDAFgCQAGgCAGAAIAkAAIAABRgAgKggQgFACgDADQgDACgBADQgBAEAAAEQAAAEABADQABAEADADQADABAFABQAEACAEAAIAbAAIAAglIgbAAQgEAAgEABg");
	this.shape.setTransform(126.7,11.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgpA9IAAh3IAIAAIAAATIAFgJIAJgGQAFgDAFgBIAJgCQAJAAAHAEQAJADAFAGQAGAGADAHQADAJAAAIQAAAJgDAIQgDAGgGAGQgFAGgJADQgHAEgJAAIgKgBIgJgFIgJgGQgDgDgCgFIAAA4gAgNgyQgHAEgEAEQgFAFgDAGQgCAHAAAHQAAAIACAGQADAFAFAFQAEAFAHADQAGADAHAAQAGAAAHgDQAGgDAFgFQAEgFADgFQADgGAAgIQAAgHgDgHQgDgGgEgFQgFgEgGgEQgHgCgGAAQgHAAgGACg");
	this.shape_1.setTransform(117.6,13);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgQAyQgIgEgFgGQgGgGgBgKQgDgIAAgLQAAgKADgKQACgKAFgHQAFgIAJgEQAJgFALgBIAZgDIABAIIgaADQgGAAgGADQgGACgFAFQgFAEgDAHQgDAIgCAKQADgFAEgEQADgEAFgCIAKgEIAIgBQAIAAAHACQAHADAFAFQAFAFADAHQADAGAAAJQAAAIgDAIQgDAHgFAFQgFAGgIADQgHADgIAAQgKAAgHgEgAgKgOQgGADgFAEQgEAEgCAFQgDAGAAAHQAAAGADAGQACAGAEAEQAEAFAGACQAGADAGAAQAGAAAGgDQAGgDAEgEQAEgEADgGQACgGAAgHQAAgHgCgFQgCgFgFgEQgEgEgFgDQgGgCgGAAQgHAAgFACg");
	this.shape_2.setTransform(107.3,10.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAZApIAAgeIgZAAIgCAAIgCAAIgTAeIgJAAIAUgfQgGgCgDgCQgEgDgCgDIgDgHIgBgHQAAgGACgEQABgFAFgEQAEgDAFgCQAGgCAGAAIAjAAIAABRgAgLggQgEACgDADQgDACgBADQgBAEAAAEQAAAEABADQABAEADADQADABAEABQAFACAFAAIAaAAIAAglIgaAAQgFAAgFABg");
	this.shape_3.setTransform(97.9,11.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgDApIAAhKIggAAIAAgHIBHAAIAAAHIggAAIAABKg");
	this.shape_4.setTransform(89.9,11.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAWApIgigmIgMAAIAAAmIgIAAIAAhRIAIAAIAAAlIAMAAIAiglIAKAAIglAoIAmApg");
	this.shape_5.setTransform(82.4,11.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgQAnQgIgDgFgGQgGgFgEgIQgCgIAAgJQAAgIACgIQAEgHAGgGQAFgGAIgDQAIgEAIAAQAJAAAHAEQAIADAGAGQAGAGADAHQADAIAAAIQAAAJgDAIQgDAIgGAFQgGAGgIADQgHAEgJAAQgIAAgIgEgAgMggQgHAEgEAEQgFAFgDAGQgCAHAAAGQAAAIACAGQADAGAFAFQAEAFAHADQAFADAHAAQAHAAAHgDQAFgDAFgFQAFgFADgGQACgGAAgIQAAgGgCgHQgDgGgFgFQgFgEgFgEQgHgCgHAAQgHAAgFACg");
	this.shape_6.setTransform(72.8,11.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgNAyQgFgCgFgEQgEgEgDgFQgCgGAAgHQAAgIAGgHQAFgHAHgDQgGgCgEgHQgEgFABgIQAAgGACgEQABgFAFgEQADgEAGgCQAFgCAFAAQAGAAAFACQAFACAEAEQAEAEADAFQACAEAAAGQAAAIgEAFQgEAGgHADQAFACACACIAHAGIADAHIABAIQAAAHgCAGQgCAFgEAEQgEAEgHACQgFADgIAAQgGAAgHgDgAgJACQgFACgDADIgFAHIgCAIQABAGABADIAFAHQADADAFACQAFACAEAAQAGAAAEgCQAFgCADgDIAFgHQACgDAAgGIgCgIIgFgHQgDgDgFgCQgEgCgGABQgEgBgFACgAgHgrIgIAEIgDAGQgCAEAAAEQAAAEACAEIADAFIAIAFQADABAEAAQAEAAAFgBQAEgCACgDQADgCABgDQACgEAAgEQAAgEgCgEIgDgGIgHgEQgEgCgFABQgEgBgDACg");
	this.shape_7.setTransform(60.2,10.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AggA0IAAgJQAAgGADgFIAHgJIAJgJIALgHIAIgHIAJgHIAGgHQACgEAAgFQAAgJgGgGQgHgGgKAAQgJAAgGAFQgGAFgEAHIgHgEQAEgJAJgFQAIgGALAAQAHAAAFACQAGACAFAEQAEAEACAFQACAFAAAGQAAAGgCAFQgDAFgEAEIgJAIIgKAHIgJAHIgJAIIgGAIQgCAEAAAEIAAABIA4AAIAAAIg");
	this.shape_8.setTransform(52.1,10.1);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgQAnQgHgDgHgGQgFgFgEgIQgDgIAAgJQAAgIADgIQAEgHAFgGQAHgGAHgDQAIgEAIAAQAJAAAIAEQAHADAGAGQAFAGAEAHQADAIAAAIQAAAJgDAIQgEAIgFAFQgGAGgHADQgIAEgJAAQgIAAgIgEgAgNggQgGAEgFAEQgEAFgDAGQgDAHABAGQgBAIADAGQADAGAEAFQAFAFAGADQAHADAGAAQAHAAAGgDQAHgDAEgFQAFgFACgGQADgGAAgIQAAgGgDgHQgCgGgFgFQgEgEgHgEQgGgCgHAAQgGAAgHACg");
	this.shape_9.setTransform(39.4,11.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAbApIAAhKIg2AAIAABKIgIAAIAAhRIBGAAIAABRg");
	this.shape_10.setTransform(29.5,11.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAFAzIAAheIgRAAIAAgHIAZAAIAABlg");
	this.shape_11.setTransform(18.3,10.2);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgRAwQgJgEgHgHQgIgHgEgKQgDgJAAgLQAAgKADgJQAEgKAIgHQAHgHAJgFQAKgEAKAAQAHAAAHACQAGACAGAEQAGADAEAFIAJAKIgHAEQgFgKgKgGQgLgGgMAAQgJAAgIADQgIAEgFAGQgGAGgEAJQgEAHAAAJQAAAJAEAJQAEAHAGAGQAFAHAIADQAIADAJABQANgBAKgGQALgHAGgKIAHAEIgIALIgMAJQgFAEgIABQgHADgHAAQgKAAgKgFg");
	this.shape_12.setTransform(7.7,10.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6, new cjs.Rectangle(0,0,133.5,21.4), null);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyvZPMAAAgydMAlfAAAMAAAAydg");
	this.shape.setTransform(120,161.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ4, new cjs.Rectangle(0,-52.5,458.1,444.1), null);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Ag/BQIAAgXIBHAAIAAAXQAAAMAKAGQAJAHANAAQALAAAHgGQAGgEAAgHIAAgYQgHgRg5ggQg3gfgIgfIAAgnQAKhBBVAAQBgABAABHIAAAQIhIAAIAAgQQAAgYgYABQgMAAgGAEQgGAFAAAHIAAAPQADASA6AhQA6AhAJAjIAAAwQAAAhgeARQgZAOgpAAQhnAAAAhQgADQBQIAAjfIBIAAIAADXQAAAHAGAIQAHAJALAAQALAAAHgJQAGgIAAgHIAAjXIBIAAIAADfQAAAogbASQgXAPgugBQhVAAgLhIgAvnBIIAAgXIBQAAIAAAXQAAAMAKAGQAJAHANgBQALABAHgGQAGgFAAgGIAAgXQgHgSg5ghQg4gegIgfIAAgnQAAgiAegRQAZgOApAAQBgAAAABIIAAAYIhIAAIAAgQQAAgYgYABQgMAAgGAEQgGAFAAAHIAAAPQADATA6AgQA6AeAJAeIAAAwQgGAigfARQgbAOgogBQhoAAAAhQgAM6CCQgcgSgGgoIAAiXQAFgnAggSQAagPApAAQAtAAAZAPQAcARAGAoIAAAYIhIAAIAAgYIgKgPQgHgJgPAAQgQAAgJAJQgHAHAAAIIAACXQAEAFAGALQAHAJAPgBQAQABAJgJQAHgIAAgIIAAgwIggAAIAAguIBoAAIAABeQgFAnggATQgaAOgpAAQgtAAgZgOgAjfCQIAAkHIgwEHIhIAAIgwkHIAAEHIhIAAIAIkfIB4AAIAgDfIAojfIBoAAIAIEfgApHCQIgokHIgoEHIhQAAIA4kfICAAAIA4EfgAJwCIIhIjvIAIDvIhIAAIAAkXIBoAAIBADnIAAjnIBIAAIAAEXg");
	this.shape.setTransform(128.1,22.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ2, new cjs.Rectangle(28.1,6.5,200,32), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.Символ10("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(269,21.4,1,1,0,0,0,100,21.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:100,alpha:1},19,cjs.Ease.cubicInOut).wait(11));

	// Слой_2
	this.instance_1 = new lib.Символ11("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(263,67.9,1,1,0,0,0,95,23.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({x:95,alpha:1},19,cjs.Ease.cubicInOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(169,0,200,42.9);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.Символ13("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(240.4,21.1,1,1,0,0,0,75.5,9.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:78.6,alpha:1},14,cjs.Ease.get(1)).wait(14));

	// Слой_3
	this.instance_1 = new lib.Символ14("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(244.5,45.5,1,1,0,0,0,80.7,5.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({x:82.8,alpha:1},16,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,315.8,56.6);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_4
	this.instance = new lib.Символ4();
	this.instance.parent = this;
	this.instance.setTransform(120,200.1,1,1.239,0,0,0,120,161.5);
	this.instance.compositeOperation = "lighter";

	this.timeline.addTween(cjs.Tween.get(this.instance).to({alpha:0},14,cjs.Ease.get(-1)).wait(175).to({alpha:1},20,cjs.Ease.cubicInOut).wait(1));

	// Слой_3
	this.instance_1 = new lib.Символ15("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(119.8,172.2,0.678,0.678,0,0,0,150.1,94.7);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({y:109.2,alpha:1},35,cjs.Ease.quadInOut).wait(165));

	// Слой_10
	this.instance_2 = new lib.Символ5("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(119,228.8,1.263,1.263,0,0,0,83.1,28.3);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(27).to({_off:false},0).wait(54).to({startPosition:27},0).to({y:178.8,alpha:0},13,cjs.Ease.cubicInOut).to({_off:true},1).wait(115));

	// Слой_11
	this.instance_3 = new lib.Символ6();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-67,276.5,1,1,0,0,0,57.5,9.5);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(61).to({_off:false},0).to({x:73.5},14,cjs.Ease.get(1)).wait(8).to({y:196.5},15,cjs.Ease.cubicInOut).wait(112));

	// Слой_7
	this.instance_4 = new lib.Символ7("synched",0,false);
	this.instance_4.parent = this;
	this.instance_4.setTransform(122.6,257.7,1.071,1.071,0,0,0,99.5,43.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(91).to({_off:false},0).wait(119));

	// Слой_2
	this.instance_5 = new lib.Символ2();
	this.instance_5.parent = this;
	this.instance_5.setTransform(48.3,17.8,0.423,0.423,0,0,0,100,16.1);

	this.instance_6 = new lib.Символ9("synched",0);
	this.instance_6.parent = this;
	this.instance_6.setTransform(211.1,18.2,1,1,0,0,0,11.1,13.2);

	this.instance_7 = new lib.Символ20("synched",0);
	this.instance_7.parent = this;
	this.instance_7.setTransform(127.5,387,1,1,0,0,0,112.5,30);
	this.instance_7.alpha = 0.551;

	this.instance_8 = new lib.ClipGroup();
	this.instance_8.parent = this;
	this.instance_8.setTransform(119.4,340.6,0.422,0.422,0,0,0,240.5,34.5);
	this.instance_8.alpha = 0.602;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5}]}).wait(210));

	// Слой_6
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#0762AC","#7AC3FD","#E5F5FE","#E5F5FE","#7AC3FD","#0863AD"],[0,0.125,0.239,0.267,0.463,1],0,-197.1,0,135.3).s().p("AyvfQMAAAg+fMAlfAAAMAAAA+fg");
	this.shape.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(210));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,240,400);


// stage content:
(lib._240x400 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("Ayv/PMAlfAAAMAAAA+fMglfAAAg");
	this.shape.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(120,200,1,1,0,0,0,120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(119,199,242,402);
// library properties:
lib.properties = {
	id: 'C6A00BBDD0286844BAA69EAD3B3A70D2',
	width: 240,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"./QE65Q80R.png", id:"QE65Q80R"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C6A00BBDD0286844BAA69EAD3B3A70D2'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;