(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [];


// symbols:



(lib.TV_s = function() {
	this.initialize(img.TV_s);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,325,317);// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.ClipGroup = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_3
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ACpCyQgtgpAAhRIAAkUIBqAAIAAENQAAAtAQAWQARAXAlAAQAkAAASgWQARgVAAgvIAAkNIBqAAIAAEUQAABQgtAqQgsArhYAAQhVgBgugqgAgeDTIh2ieIgmAAIAACeIhpAAIAAmvICqAAQAjABAaAEQAZAEAXAPQAWAOANAYQANAVAAAkQAAAygVAfQgVAeglASICNC3gAi6gXIAfAAQAWAAAPgEQAPgCALgJQAKgIAGgLQAFgNAAgRQAAgQgGgMQgHgMgOgGQgKgFgMgBQgMgBgSAAIgkAAgAncDTIAAhyIBlAAIAAByg");
	this.shape.setTransform(433.3,23);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AqSClQg3g+AAhmQAAhnA3g+QA2g8BgAAQBfAAA3A8QA3A9AABoQAABng3A9Qg2A8hgAAQhgAAg2g8gAofiHQgQAHgPASQgNARgIAcQgIAbAAAnQAAAoAHAaQAIAZANATQAPASAQAHQASAIASgBQATAAASgHQARgIANgSQAOgTAHgZQAHgbAAgnQAAgmgHgbQgJgbgMgRQgOgSgRgIQgRgHgTAAQgVAAgOAHgA2gClQg2g9AAhnQAAhoA2g9QA3g8BgAAQBfAAA3A8QA3A9AABoQAABng3A9Qg3A8hfAAQhgAAg3g8gA0tiHQgQAHgOASQgNAQgJAdQgIAeAAAkQAAAoAIAaQAIAZANATQAOASARAHQASAIASgBQATAAARgHQASgJANgRQANgTAIgZQAHgaAAgoQAAgkgIgdQgHgbgOgRQgNgSgRgIQgRgHgTAAQgVAAgPAHgAb7DZIh0ixIgUAeIAACTIhrAAIAAmwIBrAAIAADAICHjAIB7AAIiXDJICdDngATeDZIAAhMIA9AAIAAkYIg9AAIAAhMIDkAAIAABMIg9AAIAAEYIA9AAIAABMgAQzDZIijktIAAEtIhiAAIAAmwICDAAICHD2IAAj2IBhAAIAAGwgAHhDZIAAmwIBrAAIAAFdICwAAIAABTgAC3DZIAAhMIA9AAIAAkYIg9AAIAAhMIDkAAIAABMIg9AAIAAEYIA9AAIAABMgAjwDZIAAmwICDAAQAtAAAnAGQAmAGAiAWQAqAcAYAtQAYAwAAA9QAAA7gaAxQgaAwgnAZQgiAWglAGQgqAHgpAAgAiGCIIACAAQAkAAAZgCQAZgBAVgOQAagRANgeQAOgdAAgrQAAgqgOgeQgOgegegSQgWgMgXgBIg7gBgAv9DZIAAmwIBqAAIAAFdICwAAIAABTgA6ADZIAAjAIiQAAIAADAIhqAAIAAmwIBqAAIAACeICQAAIAAieIBrAAIAAGwg");
	this.shape_1.setTransform(191.5,22.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AOkBPQgTgVAAgjQAAgiATgVQAUgVAhAAQAhAAAUAVQATAVAAAiQAAAkgTAUQgTAVgiAAQgiAAgTgVgAPNgWQgFACgGAGQgEAGgDAJQgDAJgBANQABAOADAJQABAIAGAHQAFAGAGACQAFADAHABQAHgBAGgDQAGgCAFgHQAFgGACgIQACgJABgOQgBgNgCgJQgDgJgEgFQgFgGgGgDQgHgDgGAAQgGAAgGADgAJdBPQgSgVAAgjQAAgiASgVQAUgVAiAAQAhAAAUAVQASAVABAiQgBAkgSAUQgUAVghAAQgjAAgTgVgAKGgWQgGACgFAGQgFAGgCAJQgDAJAAANQAAANACAKQADAJAFAGQAGAGAFACQAGADAHABQAGgBAGgDQAHgCAEgHQAEgGADgIQADgJAAgOQAAgNgDgJQgDgJgEgFQgFgHgGgCQgHgDgFAAQgHAAgGADgAnKBhQgRgDgIgDIAAghIAEAAQAJAFALAFQANAEAKABQAPAAAKgGQAJgFAAgMQgBgJgGgFQgHgEgQgBIgWAAIAAgaIAUAAQAOAAAHgEQAHgEgBgIQAAgIgGgDQgIgDgLAAQgHAAgHACIgLADIgKAEIgHAEIgDAAIAAgfIAVgGQARgEANAAQAcAAAPAKQAPAJAAARQAAANgIAIQgHAJgNADIAAABQAGACAFACQAFADAFADQAGAFACAGQADAGAAAJQAAAXgSALQgQANggAAQgNAAgPgDgEAlAABhIAAhhIg5BhIgiAAIAAiTIAkAAIAABYIA1hYIAnAAIAACTgEAieABhIgpg7IgJAAIAAA7IgmAAIAAiTIAmAAIAAA8QAKgCADgDQAEgCAHgMIAIgQQAFgNALgHQAIgFAQAAIAOAAIAAAgIgJAAQgIAAgDAEQgGAFgEAKQgEAJgDAEQgDAFgEACIA0BMgAf1BhIAAhhIg4BhIgjAAIAAiTIAlAAIAABYIA1hYIAmAAIAACTgAdHBhIAAhCIgzAAIAABCIglAAIAAiTIAlAAIAAA2IAzAAIAAg2IAmAAIAACTgAanBhIgcgvIgdAvIgqAAIAwhKIguhJIArAAIAbAtIAcgtIApAAIgvBHIAxBMgAXIBhIAAiTIBlAAIAAAcIhAAAIAAAaIA7AAIAAAbIg7AAIAAAmIBAAAIAAAcgAVaBhIAAh3IgtAAIAAgcIB+AAIAAAcIgsAAIAAB3gAShBhIAAhhIg5BhIgjAAIAAiTIAlAAIAABYIA1hYIAnAAIAACTgAL/BhIAAiTIA1AAQAPAAAKABQAHABAIAFQAIAEAEAHQAEAGAAALQAAALgGAHQgEAIgKAEIAAABQANADAIAJQAJAJAAAPQAAAKgEAJQgEAJgIAFQgHAGgLADQgLADgOAAgAMkBGIAXAAQAHgBAEgCQAFgCACgFQACgEABgFQAAgHgDgEQgDgDgFgDQgEgBgGAAIgXAAgAMkAHIASAAIAIgCQAFgCACgDQABgDAAgFIgBgHQgDgFgEgBQgDgCgFABIgSgBgAHkBhIAAh3IgsAAIAAgcIB+AAIAAAcIgsAAIAAB3gAF1BhIAAiTIAlAAIAACTgAD1BhIAAiTIAlAAIAAA3IAXAAQAJgBAOACQAKACAJAHQAHAGAFAJQADAJAAALQAAAJgEALQgFAKgHAFQgJAHgJACQgLADgOAAgAEaBFIARAAQAMABAGgFQAHgGAAgIIgBgHQgCgEgCgCQgCgDgGgCQgEgBgIAAIgRAAgABaBhIAAiTIBsAAIAAAcIhHAAIAAAbIAZAAQAJgBAOACQAMADAHAGQAIAGAEAJQADAKAAAKQAAAKgEAKQgEAJgHAGQgJAHgKACQgLADgNAAgAB/BFIATAAQAMABAGgFQAHgGAAgIIgBgHQgBgEgDgCQgDgDgEgCQgEgBgJAAIgTAAgAhCBhIAAhCIgyAAIAABCIgmAAIAAiTIAmAAIAAA2IAyAAIAAg2IAlAAIAACTgAjrBhIAAhhIg6BhIgiAAIAAiTIAlAAIAABYIA0hYIAoAAIAACTgAobBhIgJgeIgvAAIgKAeIglAAIAziTIAoAAIAyCTgApLAoIAfAAIgQgvgAr0BhIAAiTIBlAAIAAAcIg/AAIAAB3gAs4BhIgJgeIguAAIgJAeIgmAAIAyiTIApAAIAyCTgAtnAoIAeAAIgPgvgAvhBhIAAhhIgbA+IgZAAIgbg+IAABhIgjAAIAAiTIArAAIAhBIIAhhIIAqAAIAACTgA0MBhIAAh3IgtAAIAAgcIB+AAIAAAcIgsAAIAAB3gA22BhIAAiTIBlAAIAAAcIg/AAIAAAaIA7AAIAAAbIg7AAIAAAmIA/AAIAAAcgA4IBhIAAhCIgzAAIAABCIglAAIAAiTIAlAAIAAA2IAzAAIAAg2IAlAAIAACTgA71BhIAAiTIA6AAQAMAAAKACQAJACAIAGQAJAGAEAJQAFAJgBANQAAAKgDAIQgEALgFAFIgJAIIgJAFIgMAEIgPABIgTAAIAAAwgA7PAVIAUAAIAHgCIAFgEQADgEACgEQACgDgBgHQAAgFgCgFQgDgEgFgDIgKgCIgSAAgA+BBhIAAiTIBkAAIAAAcIg/AAIAAAaIA7AAIAAAbIg7AAIAAAmIA/AAIAAAcgA/wBhIAAh3IgsAAIAAgcIB+AAIAAAcIgsAAIAAB3gEghfABhIAAhCIgzAAIAABCIglAAIAAiTIAlAAIAAA2IAzAAIAAg2IAmAAIAACTgEgkIABhIAAhhIg6BhIgiAAIAAiTIAlAAIAABYIA0hYIAnAAIAACTgAy+AjIAAgVIBGAAIAAAVgARfhGQgNgLAAgSIAgAAQAAALAFAFQAEAFALAAQALAAAEgFQAFgFAAgLIAhAAQAAASgNALQgNALgbAAQgaAAgNgLg");
	this.shape_2.setTransform(240.5,58.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.ClipGroup, new cjs.Rectangle(0,0,481,68.5), null);


(lib.Символ20 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgGAlIgHgDIgFgEIgFgGIAHgEQADAFAEACQAFADAEAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIAAgGIAEgBIAFgCIADgEIABgFQAAgGgDgDQgEgDgGAAQgEAAgEACQgDADgCAEIgHgEQADgHAGgDQAGgDAGAAQAEAAAEABIAHAEQADACACAEQACADAAAFQAAAGgDAEQgEAEgEACIAEACIAEADIADAFIABAHQAAAFgCAEQgCAEgEADQgDADgFABIgIABIgGAAg");
	this.shape.setTransform(174,29.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgGAlIgHgDIgFgEIgFgGIAHgEQADAFAEACQAFADAEAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIAAgGIAEgBIAFgCIADgEIABgFQAAgGgDgDQgEgDgGAAQgEAAgEACQgDADgCAEIgHgEQADgHAGgDQAGgDAGAAQAEAAAEABIAHAEQADACACAEQACADAAAFQAAAGgDAEQgEAEgEACIAEACIAEADIADAFIABAHQAAAFgCAEQgCAEgEADQgDADgFABIgIABIgGAAg");
	this.shape_1.setTransform(168,29.4);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgNAiQgGgDgDgGIAHgEQAEAIALAAQAGAAAEgEQAFgEgBgIQABgIgHgFQgHgEgLABIgIAAIAAghIAlAAIAAAIIgdAAIAAARIABAAIAMABQAGABAEAEQAFADACADQADAFAAAHQAAAGgCAFQgCAEgDADQgDADgFABQgEABgEAAQgHAAgGgCg");
	this.shape_2.setTransform(162.3,29.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgUAlIAAgFIAMgOIAJgMIAEgGIAEgFIACgFIABgFQAAgGgDgEQgEgDgFAAQgJAAgGALIgHgEQAEgHAFgEQAGgEAIAAQAEAAAEACIAHAEIAEAGIABAIQAAAHgDAGIgJALIgJALIgIAKIAfAAIAAAIg");
	this.shape_3.setTransform(156.3,29.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgLAkIAag/IgnAAIAAgIIAxAAIAAAGIgaBBg");
	this.shape_4.setTransform(150.3,29.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQAfIAKgEIAHgFQADgCADgEIAFgIIgHACIgGABQgFAAgEgCIgGgFIgFgHQgBgEAAgFQAAgFABgFQACgEADgDIAHgFQAEgCAFAAQAGAAAEACQAEADADAEQADAEACAFQABAFAAAGQAAAIgCAHQgDAIgFAGQgFAGgHAEQgHAEgIABgAgGgbIgFADIgCAGIAAAGIAAAGIADAGIAFADQADABACAAIAHgBIAGgDIABgHIgBgIIgCgHIgFgFQgDgCgDAAQgEAAgCACg");
	this.shape_5.setTransform(144.5,29.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgQAfIAKgEIAGgFQAFgCACgEIAFgIIgGACIgHABQgFAAgEgCIgHgFIgEgHQgBgEAAgFQAAgFABgFQACgEADgDIAHgFQAEgCAFAAQAGAAAEACQAEADADAEQADAEACAFQABAFAAAGQAAAIgCAHQgEAIgEAGQgGAGgHAEQgFAEgJABgAgGgbIgFADIgCAGIAAAGIAAAGIADAGIAFADQADABACAAIAHgBIAGgDIABgHIgBgIIgCgHIgFgFQgDgCgDAAQgDAAgDACg");
	this.shape_6.setTransform(138.5,29.4);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgGAlIgHgDIgFgEIgFgGIAHgEQADAFAEACQAFADAEAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIAAgGIAEgBIAFgCIADgEIABgFQAAgGgDgDQgEgDgGAAQgEAAgEACQgDADgCAEIgHgEQADgHAGgDQAGgDAGAAQAEAAAEABIAHAEQADACACAEQACADAAAFQAAAGgDAEQgEAEgEACIAEACIAEADIADAFIABAHQAAAFgCAEQgCAEgEADQgDADgFABIgIABIgGAAg");
	this.shape_7.setTransform(132.3,29.4);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgLAkIAag/IgnAAIAAgIIAxAAIAAAGIgaBBg");
	this.shape_8.setTransform(126.5,29.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgLAkIAag/IgnAAIAAgIIAxAAIAAAGIgaBBg");
	this.shape_9.setTransform(120.6,29.5);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgGAlIgHgDIgFgEIgFgGIAHgEQADAFAEACQAFADAEAAIAFgBIAFgDIADgEIABgGIgBgGIgDgEIgFgDIgFgBIAAgGIAEgBIAFgCIADgEIABgFQAAgGgDgDQgEgDgGAAQgEAAgEACQgDADgCAEIgHgEQADgHAGgDQAGgDAGAAQAEAAAEABIAHAEQADACACAEQACADAAAFQAAAGgDAEQgEAEgEACIAEACIAEADIADAFIABAHQAAAFgCAEQgCAEgEADQgDADgFABIgIABIgGAAg");
	this.shape_10.setTransform(114.5,29.4);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgLAiQgFgDgDgFQgDgFgCgHQgBgHAAgHQAAgGABgHQACgGADgGQADgFAFgDQAFgDAGAAQAHAAAFADQAFADADAFQADAGACAGIABANQAAAHgBAHQgCAHgDAFQgDAFgFADQgFADgHAAQgGAAgFgDgAgHgaIgFAHIgDAJIgBAKIABALQABAFACAEQACAFADACQADADAEAAQAEAAAEgDQADgCACgFIADgJIABgLIgBgKIgDgJQgCgEgDgDQgEgCgEAAQgEAAgDACg");
	this.shape_11.setTransform(108.7,29.4);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAGAkIAAg9IgQAKIgEgGIAVgOIAIAAIAABHg");
	this.shape_12.setTransform(102.2,29.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgbAEIAAgHIA2AAIAAAHg");
	this.shape_13.setTransform(94.9,30.2);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AASAlIAAgiIgkAAIAAAiIgIAAIAAhJIAIAAIAAAgIAkAAIAAggIAJAAIAABJg");
	this.shape_14.setTransform(86.3,29.4);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgXAlIAAhJIAXAAQAMAAAGAGQAGAGAAALQAAAKgHAFQgGAFgLAAIgOAAIAAAegAgOAAIAOAAQAGAAAEgDQAEgDAAgIQAAgHgEgEQgDgDgHAAIgOAAg");
	this.shape_15.setTransform(80,29.4);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgUAlIAAhJIApAAIAAAIIghAAIAABBg");
	this.shape_16.setTransform(74.4,29.4);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgNAjQgGgDgEgGQgDgFgCgHQgCgHAAgHQAAgGACgHQACgHADgFQAEgGAGgDQAGgDAHAAQAIAAAGADQAFADAEAGQAEAFACAHQACAHAAAGQAAAHgCAHQgCAHgEAFQgEAGgFADQgGADgIAAQgHAAgGgDgAgJgbQgEADgCAEQgDAEgBAGQgCAFAAAFQAAAGACAFQABAGADAEQACAEAEADQAFACAEAAQAGAAAEgCQADgDAEgEQACgEABgGIABgLIgBgKQgBgGgCgEQgDgEgEgDQgEgCgGAAQgEAAgFACg");
	this.shape_17.setTransform(67.8,29.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgHAIIAEgCQABgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgCgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQACADAAADIgCAEIgDAFIgEADIgFADg");
	this.shape_18.setTransform(60.7,33);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgLAiQgFgDgDgFQgDgFgCgHQgBgHAAgHIABgNQACgGADgGQADgFAFgDQAFgDAGAAQAHAAAFADQAFADADAFQADAGACAGIABANQAAAHgBAHQgCAHgDAFQgDAFgFADQgFADgHAAQgGAAgFgDgAgHgaIgFAHIgDAJIgBAKIABALQABAFACAEQACAFADACQADADAEAAQAEAAAEgDQADgCACgFIADgJIABgLIgBgKIgDgJQgCgEgDgDQgEgCgEAAQgEAAgDACg");
	this.shape_19.setTransform(56.7,29.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAGAkIAAg9IgPAKIgFgGIAVgOIAIAAIAABHg");
	this.shape_20.setTransform(50.2,29.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgDAFQgCgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABABQAAAAAAABQABAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape_21.setTransform(220.7,22.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AASAaIAAglIgRAlIgBAAIgRglIAAAlIgIAAIAAgzIAKAAIAPAlIAQglIAKAAIAAAzg");
	this.shape_22.setTransform(216.1,20.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgJAZQgFgCgEgEQgCgEgCgFIgCgKIACgJQACgFACgEQADgEAFgCQAFgCAFgBQAGABAEACQAGACACAEQADAEACAFIACAJQgBAFgBAFQgCAGgDADQgCAEgGACQgEACgGAAQgFAAgEgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_23.setTransform(209.8,20.1);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AANAaIAAgsIgZAAIAAAsIgJAAIAAgzIArAAIAAAzg");
	this.shape_24.setTransform(203.9,20.1);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgHAIIAEgCQABgBABAAQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQABADAAADIgBAEIgEAFIgEADIgFADg");
	this.shape_25.setTransform(197.4,22.6);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AAGAkIAAg9IgQAKIgEgGIAVgOIAIAAIAABHg");
	this.shape_26.setTransform(192.9,19.1);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgEAFQgBgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAgBQABAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAABQAAAAAAABQABAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBgBAAg");
	this.shape_27.setTransform(189.4,22.2);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AANAaIAAgsIgZAAIAAAsIgIAAIAAgzIApAAIAAAzg");
	this.shape_28.setTransform(185.4,20.1);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgVAmIAAhJIAHgBIABAFQADgDAEgBIAHgCQAGABAEACQAEACACAEQADAEACAEIABAKQAAAHgDAEQgBAFgEAEQgDAEgFABQgFACgEAAQgHAAgEgBIAAAWgAgHgcIgGAEIAAAgIADACIAGABQAEAAACgCIAGgDQADgDACgDQABgEAAgFIAAgIIgDgGQgCgDgDgCQgDgCgDAAIgHACg");
	this.shape_29.setTransform(179.7,21.1);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AgJAZQgFgCgEgEQgCgEgCgFIgCgKIACgJQACgFACgEQADgEAFgCQAFgCAFgBQAGABAEACQAGACACAEQADAEACAFIACAJQgBAFgBAFQgCAGgDADQgCAEgGACQgEACgGAAQgFAAgEgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_30.setTransform(173.8,20.1);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AALAaIgPgXIgJAAIAAAXIgIAAIAAgzIAIgBIAAAXIAGAAIADgBIABgBIADgEIABgFIADgFIADgEIADgCIAFAAIAFAAIAAAHIgDAAQgDAAgCABQgCABgCAFIgEAHIgCADIATAbg");
	this.shape_31.setTransform(168.6,20.1);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgHAIIAFgCQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgBgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQABADAAADIgBAEIgEAFIgEADIgFADg");
	this.shape_32.setTransform(162.2,22.6);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgJAjQgFgCgDgEQgDgEgBgFIgBgLQAAgJACgHQADgIAFgGQAFgGAHgEQAFgEAJgBIACAHIgJADIgHAFQgEADgCAEQgEAEgBAEIAHgDIAGgBQAFAAAEACQAEACACADQAEADABAEIABAKQAAAFgBAEQgCAEgDAEQgDADgEACQgEABgFAAQgFAAgFgCgAgGgBQgDABgDABIgBAIIABAHIACAHIAFAFQADACADAAQADAAADgBIAEgEQACgCABgDIAAgGIAAgHIgDgFIgFgDQgDgBgDAAIgGABg");
	this.shape_33.setTransform(158.3,19.1);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AAGAkIAAg9IgQAKIgEgGIAVgOIAIAAIAABHg");
	this.shape_34.setTransform(151.7,19.1);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AgDAFQgCgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABABQAAAAAAABQABAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape_35.setTransform(148.2,22.2);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AATAgIAAgMIgmAAIAAAMIgIAAIAAgTIADAAQAEgCACgDQACgEABgEIABgJIABgJIAAgNIAjAAIAAAsIAGAAIAAATgAgFgPIAAAIIgCAHIgCAIIgEAFIAaAAIAAglIgSAAg");
	this.shape_36.setTransform(144,20.7);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgHAIIAFgCQAAgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgCgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQACADAAADIgCAEIgDAFIgEADIgFADg");
	this.shape_37.setTransform(137.5,22.6);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#FFFFFF").s().p("AANAaIAAgSIgOAAQgBAGgCAEIgEAFIgEADIgDAAIgGAAIAAgHIADAAIACAAIADgBIACgEIACgHIgDgCIgEgDIgCgEIgBgGQAAgIAFgFQAGgEAJAAIAVAAIAAAzgAgHgQQgEADAAAFQAAAFADACQADACAFAAIANAAIAAgTIgNAAQgEAAgDACg");
	this.shape_38.setTransform(133.6,20.1);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgDAAgDQAAgHADgDQADgCAFgCQAEgDAFAAIALgCIAAgBQAAgGgDgDQgDgDgFAAQgDABgDABQgDABgCAEIgGgFQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEABgDAAIgHgBgAAEAAIgHABQgDACgCACQgCADAAAEIABAEIACACIADADIAEAAQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_39.setTransform(128.4,20.1);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#FFFFFF").s().p("AALAaIgPgXIgIAAIAAAXIgIAAIAAgzIAIgBIAAAXIAFAAIADgBIACgBIACgEIABgFIADgFIADgEIADgCIAFAAIAFAAIgBAHIgCAAQgDAAgCABQgCABgCAFIgDAHIgDADIATAbg");
	this.shape_40.setTransform(123.8,20.1);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#FFFFFF").s().p("AgGAaQgEgCgEgDQgDgDgCgFQgCgGAAgHQAAgGACgFQACgFADgEQAEgDAEgCQAEgCAEAAQAEABADABIAGAEIAEADIACAFIgGADQgCgFgEgCQgDgCgEgBIgFACIgFAEQgCACgCAEIgBAIIABAJQACAEACADIAFADQADACADAAQAEAAADgDQAEgCACgEIAGAEQgDAFgFADQgGADgGAAIgIgBg");
	this.shape_41.setTransform(118.4,20.1);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#FFFFFF").s().p("AANAaIAAgXIgZAAIAAAXIgJAAIAAgyIAJgCIAAAXIAZAAIAAgWIAIAAIAAAzg");
	this.shape_42.setTransform(112.7,20.1);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgDAAgDQAAgHADgDQADgCAFgCQAEgDAFAAIALgCIAAgBQAAgGgDgDQgDgDgFAAQgDABgDABQgDABgCAEIgGgFQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEABgDAAIgHgBgAAEAAIgHABQgDACgCACQgCADAAAEIABAEIACACIADADIAEAAQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_43.setTransform(107,20.1);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#FFFFFF").s().p("AgHAbQgDgBgCgCIgFgDIgDgFIAHgEIACAEIADACIAEADIAFAAQAGAAADgCQADgDAAgEQAAgEgDgCQgCgCgEgBIgEAAIgEAAIAAgFIAEAAIADgBQAEgBADgCQACgCAAgEQAAgEgEgCQgDgCgEAAQgJAAgEAKIgGgCQACgIAFgDQAFgDAHgBQAJAAAFAFQAFADAAAHQAAAEgDAEQgDADgEABQAFAAADADQADADAAAFQAAAIgGAFQgFADgKAAIgHAAg");
	this.shape_44.setTransform(102.1,20.1);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#FFFFFF").s().p("AANAaIAAgSIgOAAQgBAGgCAEIgEAFIgEADIgDAAIgGAAIAAgHIADAAIACAAIADgBIACgEIACgHIgDgCIgEgDIgCgEIgBgGQAAgIAFgFQAGgEAJAAIAVAAIAAAzgAgHgQQgEADAAAFQAAAFADACQADACAFAAIANAAIAAgTIgNAAQgEAAgDACg");
	this.shape_45.setTransform(96.9,20.1);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#FFFFFF").s().p("AgWAmIAAhJIAIgBIABAFQADgDAEgBIAHgCQAGABAEACQAEACADAEQACAEABAEIABAKQAAAHgCAEQgCAFgDAEQgDAEgFABQgFACgEAAQgHAAgEgBIAAAWgAgHgcIgGAEIAAAgIAEACIAFABQAEAAACgCIAHgDQACgDABgDQACgEAAgFIgBgIIgCgGQgCgDgDgCQgDgCgDAAIgHACg");
	this.shape_46.setTransform(91.8,21.1);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#FFFFFF").s().p("AgJAZQgFgCgDgEQgDgEgCgFIgCgKIACgJQACgFADgEQADgEAEgCQAFgCAFgBQAGABAEACQAFACAEAEQADAEABAFIACAJQAAAFgCAFQgBAGgDADQgEAEgFACQgEACgGAAQgFAAgEgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_47.setTransform(85.8,20.1);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#FFFFFF").s().p("AgVAmIAAhJIAHgBIABAFQAEgDADgBIAHgCQAGABAEACQAEACADAEQACAEABAEIACAKQgBAHgCAEQgCAFgDAEQgDAEgFABQgFACgEAAQgHAAgEgBIAAAWgAgHgcIgGAEIAAAgIAEACIAFABQAEAAACgCIAGgDQADgDABgDQACgEAAgFIAAgIIgDgGQgCgDgDgCQgDgCgDAAIgHACg");
	this.shape_48.setTransform(80.2,21.1);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgDAAgDQAAgHADgDQADgCAFgCQAEgDAFAAIALgCIAAgBQAAgGgDgDQgDgDgFAAQgDABgDABQgDABgCAEIgGgFQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEABgDAAIgHgBgAAEAAIgHABQgDACgCACQgCADAAAEIABAEIACACIADADIAEAAQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_49.setTransform(74.4,20.1);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#FFFFFF").s().p("AgEAaIAAgsIgRAAIAAgHIArAAIgBAHIgRAAIAAAsg");
	this.shape_50.setTransform(69.9,20.1);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#FFFFFF").s().p("AgIAkQgFgCgFgFQgEgEgCgHQgCgIAAgKQAAgJADgHQACgIAEgEQAEgFAFgCQAGgCAEAAQAIAAAHAEQAGAEADAHIgGAEIgDgEIgEgDIgFgDQgCgBgDAAQgJAAgFAIQgGAIAAANQAAAIACAFQABAGADAEQADADAEACQAEACAEAAIAFgBIAFgCIADgEIAEgEIAGAEIgEAGIgFAEQgDADgDABQgEABgEAAQgGAAgGgCg");
	this.shape_51.setTransform(64.7,19);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#FFFFFF").s().p("AgDAFQgCgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBABgBQAAAAABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAQAAABABABQAAAAAAABQABAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape_52.setTransform(60.4,22.2);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#FFFFFF").s().p("AAQAaIAAgsIgSAAIAAASIgCANQgCAGgDAEQgEADgHAAIgDAAIAAgHIACAAIADAAIACgBIACgCIACgFIABgFIAAgGIABgKIAAgPIAiAAIAAAzg");
	this.shape_53.setTransform(56,20.1);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#FFFFFF").s().p("AgUAlIgEgCIACgGIAEABIAEAAIADgBIAEgFIADgKIgUgyIAKAAIAOAnIAPgnIAKAAIgaBBQgCAFgDACQgEABgEAAIgGAAg");
	this.shape_54.setTransform(51.1,21.2);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#FFFFFF").s().p("AgHAIIAFgCQAAgBABAAQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQABADAAADIgBAEIgEAFIgEADIgFADg");
	this.shape_55.setTransform(45.1,22.6);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgDAAgDQAAgHADgDQADgCAFgCQAEgDAFAAIALgCIAAgBQAAgGgDgDQgDgDgFAAQgDABgDABQgDABgCAEIgGgFQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEABgDAAIgHgBgAAEAAIgHABQgDACgCACQgCADAAAEIABAEIACACIADADIAEAAQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_56.setTransform(41.4,20.1);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#FFFFFF").s().p("AATAgIAAgMIgmAAIAAAMIgIAAIAAgTIADAAQADgCACgDQADgEABgEIACgJIAAgJIAAgNIAjAAIAAAsIAGAAIAAATgAgFgPIAAAIIgCAHIgCAIIgEAFIAbAAIAAglIgTAAg");
	this.shape_57.setTransform(35.8,20.7);

	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("AgJAZQgFgCgDgEQgEgEgBgFIgCgKIACgJQABgFAEgEQADgEAEgCQAFgCAFgBQAGABAFACQAFACADAEQADAEABAFIABAJQAAAFgBAFQgBAGgDADQgDAEgFACQgFACgGAAQgFAAgEgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_58.setTransform(29.9,20.1);

	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#FFFFFF").s().p("AgKAkQgFgDgDgDQgDgEgBgGIgBgNQAAgSAFgLQAGgJAMgBIAFAAIAFAAQACgCAAgDIAHACQgBAGgDADQgDABgHABIgFAAIgHACIgEAFIgDAGIgBAGQADgEAEgCQAEgCAGAAQAFAAAEACQAFACACAEQADADACAEQABAEAAAGQAAAFgBAEQgCAFgDAEQgDAEgFACQgEACgGAAQgGAAgEgCgAgGgFIgFAEIgDAGIgBAHIABAHIADAGQACADADACQADABADAAQAEAAADgBQADgCACgDIADgGIABgHIgBgHIgDgFQgCgDgDgCQgDgBgEAAQgDAAgDABg");
	this.shape_59.setTransform(24,19);

	this.shape_60 = new cjs.Shape();
	this.shape_60.graphics.f("#FFFFFF").s().p("AgKAZQgEgCgDgEQgEgEgBgFQgCgFABgFQgBgEACgFQABgFAEgEQADgEAEgCQAFgCAFgBQAGABAFACQAEACAEAEQADAEABAFIABAJQAAAFgBAFQgBAGgDADQgEAEgEACQgFACgGAAQgFAAgFgCgAgGgSIgFAFIgDAGIgBAHIABAHIADAIQACADADABQADACADAAQAEAAADgCQADgBACgDIADgIIABgHIgBgHIgDgGIgFgFQgDgBgEgBQgDABgDABg");
	this.shape_60.setTransform(18.1,20.1);

	this.shape_61 = new cjs.Shape();
	this.shape_61.graphics.f("#FFFFFF").s().p("AAQAaIAAgsIgSAAIAAASIgCANQgCAGgDAEQgEADgHAAIgDAAIAAgHIACAAIADAAIACgBIACgCIACgFIABgFIAAgGIABgKIAAgPIAiAAIAAAzg");
	this.shape_61.setTransform(11.9,20.1);

	this.shape_62 = new cjs.Shape();
	this.shape_62.graphics.f("#FFFFFF").s().p("AgIAkQgFgCgFgFQgDgEgDgHQgCgIAAgKQAAgJACgHQADgIAEgEQAEgFAFgCQAFgCAFAAQAJAAAGAEQAGAEADAHIgHAEIgCgEIgEgDIgFgDQgCgBgDAAQgJAAgFAIQgGAIAAANQAAAIACAFQACAGADAEQACADAEACQAEACAEAAIAFgBIAFgCIADgEIADgEIAHAEIgDAGIgGAEQgDADgDABQgEABgEAAQgGAAgGgCg");
	this.shape_62.setTransform(6.5,19);

	this.shape_63 = new cjs.Shape();
	this.shape_63.graphics.f("#FFFFFF").s().p("AANAaIAAgSIgOAAQgBAGgCAEIgEAFIgEADIgDAAIgGAAIAAgHIADAAIACAAIADgBIACgEIACgHIgDgCIgEgDIgCgEIgBgGQAAgIAFgFQAGgEAJAAIAVAAIAAAzgAgHgQQgEADAAAFQAAAFADACQADACAFAAIANAAIAAgTIgNAAQgEAAgDACg");
	this.shape_63.setTransform(213.4,9.5);

	this.shape_64 = new cjs.Shape();
	this.shape_64.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgCAAgFQAAgFADgEQADgCAFgCQAEgDAFgBIALgBIAAgBQAAgGgDgDQgDgCgFAAQgDgBgDACQgDACgCACIgGgEQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEACgDgBIgHgBgAAEAAIgHABQgDABgCADQgCACAAAEIABAFIACACIADACIAEABQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_64.setTransform(208.2,9.5);

	this.shape_65 = new cjs.Shape();
	this.shape_65.graphics.f("#FFFFFF").s().p("AAMAaIgQgYIgJAAIAAAYIgIAAIAAgzIAIgBIAAAXIAHAAIACgBIABgCIADgCIABgGIADgFIADgEIAEgCIAEAAIAFAAIAAAHIgDAAQgDAAgCABQgCACgCAEIgEAHIgCAEIATAag");
	this.shape_65.setTransform(203.6,9.5);

	this.shape_66 = new cjs.Shape();
	this.shape_66.graphics.f("#FFFFFF").s().p("AgGAaQgEgCgEgDQgDgDgCgGQgCgEAAgIQAAgGACgFQACgGADgDQAEgDAEgCQAEgCAEAAQAEABADABIAGAEIAEAEIACADIgGAFQgCgGgEgCQgDgDgEABIgFABIgFAEQgCADgCADIgBAIIABAJQACAEACADIAFADQADACADAAQAEAAADgDQAEgBACgGIAGAFQgDAGgFADQgGACgGAAIgIgBg");
	this.shape_66.setTransform(198.2,9.5);

	this.shape_67 = new cjs.Shape();
	this.shape_67.graphics.f("#FFFFFF").s().p("AgUAaIAAgzIAWAAQAIAAAEADQAEADAAAHQAAAFgCADQgDADgDABIAEAAIADACIADAEIABAFQAAAIgFADQgFAEgHAAgAgLATIAOAAIADAAIADgBIACgDIABgEQAAgDgCgDQgDgCgFAAIgNAAgAgLgDIAMAAQAFAAACgCQACgDAAgDQAAgHgIAAIgNAAg");
	this.shape_67.setTransform(193,9.5);

	this.shape_68 = new cjs.Shape();
	this.shape_68.graphics.f("#FFFFFF").s().p("AgJAaQgFgDgDgEQgDgEgCgFIgCgKIACgJQACgFADgEQADgEAEgCQAFgCAFgBQAGABAEACQAFADAEAEQACADACAFIACAJQAAAGgCAEQgCAFgCAEQgEAEgFADQgEABgGAAQgFAAgEgBgAgGgSIgFAFIgDAGIgBAHIABAIIADAHQACADADABQADACADAAQAEAAADgCQADgBACgDIADgHIABgIIgBgHIgDgGIgFgFQgDgCgEABQgDgBgDACg");
	this.shape_68.setTransform(187.2,9.5);

	this.shape_69 = new cjs.Shape();
	this.shape_69.graphics.f("#FFFFFF").s().p("AAQAaIAAgsIgSAAIAAASIgCANQgCAGgDAEQgEADgHAAIgDAAIAAgHIACAAIADAAIACgBIACgCIACgFIABgFIAAgGIABgKIAAgPIAiAAIAAAzg");
	this.shape_69.setTransform(181,9.5);

	this.shape_70 = new cjs.Shape();
	this.shape_70.graphics.f("#FFFFFF").s().p("AANAmIAAgjIgZAdIAAAGIgIAAIAAgzIAIgBIAAAkIAZgcIAAgHIAIAAIAAAzgAgEgXIgGgCQgCgCgCgEQgCgCAAgFIAHAAIACAFIACACIAEACIACAAIADAAIAEgCIACgCIACgFIAHAAQAAAFgCACQgCAEgCACIgGACIgGABIgFgBg");
	this.shape_70.setTransform(175.6,8.3);

	this.shape_71 = new cjs.Shape();
	this.shape_71.graphics.f("#FFFFFF").s().p("AgIAaIgGgCIgEgGQgBgCAAgFQAAgFADgEQADgCAFgCQAEgDAFgBIALgBIAAgBQAAgGgDgDQgDgCgFAAQgDgBgDACQgDACgCACIgGgEQADgEAFgCQAEgCAGgBQAIABAFAEQAFAFAAAKIAAAhIgIAAIAAgEQgDADgDABQgEACgDgBIgHgBgAAEAAIgHABQgDABgCADQgCACAAAEIABAFIACACIADACIAEABQADAAADgCIAGgDIAAgQIgIAAg");
	this.shape_71.setTransform(169.9,9.5);

	this.shape_72 = new cjs.Shape();
	this.shape_72.graphics.f("#FFFFFF").s().p("AANAaIgNgTIgMATIgJAAIARgaIgQgZIAJAAIALATIAMgTIAJAAIgRAZIASAag");
	this.shape_72.setTransform(165.3,9.5);

	this.shape_73 = new cjs.Shape();
	this.shape_73.graphics.f("#FFFFFF").s().p("AANAaIAAgiIgZAcIAAAGIgIAAIAAgzIAIgBIAAAkIAZgcIAAgHIAIAAIAAAzg");
	this.shape_73.setTransform(160.1,9.5);

	this.shape_74 = new cjs.Shape();
	this.shape_74.graphics.f("#FFFFFF").s().p("AAAAlIgWg4IAAA3IgJAAIAAhIIAKAAIAVA4IAWg4IAKAAIAABIIgIAAIAAg3IgYA4g");
	this.shape_74.setTransform(153.2,8.5);

	this.shape_75 = new cjs.Shape();
	this.shape_75.graphics.f("#FFFFFF").s().p("AgEAFQgBgCAAgDQAAAAAAAAQAAgBAAAAQABgBAAAAQAAgBAAAAQABgBABAAQAAgBABAAQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABAAAAABQABAAAAABQABAAAAABQAAAAAAABQABAAAAABQAAAAAAAAQAAADgCACQAAAAgBABQAAAAgBAAQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBgBgBAAg");
	this.shape_75.setTransform(145.8,11.6);

	this.shape_76 = new cjs.Shape();
	this.shape_76.graphics.f("#FFFFFF").s().p("AgGAaQgEgCgEgDQgDgDgCgGQgCgEAAgIQAAgGACgFQACgGADgDQAEgDAEgCQAEgCAEAAQAEABADABIAGAEIAEAEIACADIgGAFQgCgGgEgCQgDgDgEABIgFABIgFAEQgCADgCADIgBAIIABAJQACAEACADIAFADQADACADAAQAEAAADgDQAEgBACgGIAGAFQgDAGgFADQgGACgGAAIgIgBg");
	this.shape_76.setTransform(142.2,9.5);

	this.shape_77 = new cjs.Shape();
	this.shape_77.graphics.f("#FFFFFF").s().p("AgHAIIAFgCQAAgBABAAQAAAAABgBQAAAAAAgBQAAAAAAgBIgBgCQgBAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABABAAQABADAAADIgBAEIgEAFIgEADIgFADg");
	this.shape_77.setTransform(136,12.1);

	this.shape_78 = new cjs.Shape();
	this.shape_78.graphics.f("#FFFFFF").s().p("AgNAjQgGgDgDgGQgEgFgDgHIgBgOQAAgGABgHQADgHAEgFQADgGAGgDQAGgDAHAAQAIAAAGADQAGADADAGQAEAFACAHQACAHAAAGQAAAHgCAHQgCAHgEAFQgDAGgGADQgGADgIAAQgHAAgGgDgAgJgbQgEADgCAEQgEAEgBAGQgBAFAAAFIABALQACAGADAEQACAEAEADQAFACAEAAQAFAAAFgCQADgDADgEQADgEACgGIABgLIgBgKQgCgGgDgEQgCgEgEgDQgFgCgFAAQgEAAgFACg");
	this.shape_78.setTransform(131.4,8.5);

	this.shape_79 = new cjs.Shape();
	this.shape_79.graphics.f("#FFFFFF").s().p("AAAAlIgXg4IAAA3IgIAAIAAhIIAKAAIAVA4IAVg4IALAAIAABIIgIAAIAAg3IgYA4g");
	this.shape_79.setTransform(123.7,8.5);

	this.shape_80 = new cjs.Shape();
	this.shape_80.graphics.f("#FFFFFF").s().p("AgHAIIAEgCQABgBABAAQAAAAAAgBQABAAAAgBQAAAAAAgBIgCgCQAAAAAAAAQAAgBgBAAQAAgBAAAAQAAgBAAgBQAAgDACgCQAAAAABgBQAAAAAAAAQAAgBABAAQAAAAABAAQABAAAAAAQABAAAAABQABAAAAAAQABABAAAAQACADAAADIgCAEIgDAFIgEADIgFADg");
	this.shape_80.setTransform(116.1,12.1);

	this.shape_81 = new cjs.Shape();
	this.shape_81.graphics.f("#FFFFFF").s().p("AgDAPIAQgPIgOgOIAIgIIAXAWIgZAXgAgdAPIASgPIgQgOIAJgIIAWAWIgYAXg");
	this.shape_81.setTransform(112,9.4);

	this.shape_82 = new cjs.Shape();
	this.shape_82.graphics.f("#FFFFFF").s().p("AgHAaIAAgoIgRAAIAAgMIAxAAIgCAMIgQAAIAAAog");
	this.shape_82.setTransform(106.3,9.5);

	this.shape_83 = new cjs.Shape();
	this.shape_83.graphics.f("#FFFFFF").s().p("AgYAmIAAhIIANgCIABAFIAFgEQADgCAEAAQAGAAAEACQAEADADADQADAEACAFQABAFAAAGIgBAJQgCAFgEAEQgDAEgGADQgEACgHAAIgEAAIgDgCIAAAWgAgGgYIgDAEIAAAZIAGABQADAAADgBIAFgEIACgEIABgGIgBgGIgCgFQgBgDgCgBQgDgBgCAAQgDAAgDABg");
	this.shape_83.setTransform(100.9,10.5);

	this.shape_84 = new cjs.Shape();
	this.shape_84.graphics.f("#FFFFFF").s().p("AgLAaQgFgDgDgEQgEgEgBgFIgCgKQAAgEACgFQABgFAEgEQADgEAFgCQAFgDAGAAQAHAAAFADQAFACADAEQADAEACAFQACAFAAAEQAAAFgCAFQgCAFgDAEQgDAEgFADQgFACgHAAQgGAAgFgCgAgFgOIgEAEIgCAFIgBAFIABAGIACAFIAEAEQADABACAAQADAAACgBQADgBABgDIADgFIAAgGIAAgFIgDgFQgBgDgDgBQgCgBgDAAQgCAAgDABg");
	this.shape_84.setTransform(94.6,9.5);

	this.shape_85 = new cjs.Shape();
	this.shape_85.graphics.f("#FFFFFF").s().p("AAKAaIAAgoIgTAAIAAAoIgPAAIAAg0IAwAAIAAA0g");
	this.shape_85.setTransform(88.4,9.5);

	this.shape_86 = new cjs.Shape();
	this.shape_86.graphics.f("#FFFFFF").s().p("AAQAaIAAgcIgNAcIgEAAIgOgcIAAAcIgOAAIAAg0IAOAAIAPAgIAQggIAOAAIAAA0g");
	this.shape_86.setTransform(81.5,9.5);

	this.shape_87 = new cjs.Shape();
	this.shape_87.graphics.f("#FFFFFF").s().p("AAOAlIAAgrIgcAgIAAALIgPAAIAAhJIAPAAIAAArIAcggIAAgLIAPAAIAABJg");
	this.shape_87.setTransform(74,8.5);

	this.shape_88 = new cjs.Shape();
	this.shape_88.graphics.f("#FFFFFF").s().p("AgNAGIAAgLIAbAAIAAALg");
	this.shape_88.setTransform(68.4,9.2);

	this.shape_89 = new cjs.Shape();
	this.shape_89.graphics.f("#FFFFFF").s().p("AANAaIAAgoIgNAAIAAAGIAAAIIgBAEIAAAEIgBAEQgCAGgEAFQgEADgIAAIgGAAIAAgLIADAAIAEgBQADgCAAgDIABgCIAAgFIAAgEIAAgIIAAgQIAqAAIAAA0g");
	this.shape_89.setTransform(63.1,9.5);

	this.shape_90 = new cjs.Shape();
	this.shape_90.graphics.f("#FFFFFF").s().p("AALAbIAAgcIgVAUIAAAIIgOAAIAAgyIAOgDIAAAdIAVgTIAAgJIAOAAIAAA0g");
	this.shape_90.setTransform(57.1,9.5);

	this.shape_91 = new cjs.Shape();
	this.shape_91.graphics.f("#FFFFFF").s().p("AARAgIAAgLIghAAIAAALIgNAAIAAgXIAEAAQAGgGADgIQACgJAAgLIAAgGIAnAAIAAAoIAFAAIAAAXgAgDgDQgDAHgDAFIAUAAIAAgdIgMAAQAAAJgCAIg");
	this.shape_91.setTransform(50.4,10.1);

	this.shape_92 = new cjs.Shape();
	this.shape_92.graphics.f("#FFFFFF").s().p("AgRAjQgHgEgEgJIALgHQADAFAEADQAEACAFAAIAGgBQADgBABgCIAFgGIABgJIgaAAIAAgMIAaAAQgBgJgFgFQgFgEgFAAQgGAAgDADQgEADgDAEIgMgHIAFgHIAGgFIAIgDQAFgBAFAAQAGAAAFACQAGACAEAFQAEAEACAIQADAHAAAJQAAAJgCAIQgCAHgEAFQgFAEgGADQgFACgHAAQgKAAgGgDg");
	this.shape_92.setTransform(43.8,8.5);

	this.shape_93 = new cjs.Shape();
	this.shape_93.graphics.f("#FFFFFF").s().p("AgDAAIAWgWIAJAIIgPAOIARAPIgJAIgAgdAAIAXgWIAJAIIgPAOIAQAPIgIAIg");
	this.shape_93.setTransform(37.4,9.4);

	this.shape_94 = new cjs.Shape();
	this.shape_94.graphics.f("#FFFFFF").s().p("AgOAjQgGgDgFgGQgEgFgCgHQgCgHAAgHQAAgGACgHQACgHAEgFQAFgGAGgDQAGgDAIAAQAIAAAHADQAGADAEAGQAEAFADAHQACAHAAAGQAAAHgCAHQgDAHgEAFQgEAGgGADQgHADgIAAQgIAAgGgDgAgIgWQgDACgCAEIgEAIIgBAIIABAJIAEAJQACADADACQAEACAEAAQAEAAAEgCQADgCADgDQADgEAAgFIABgJIgBgIQAAgFgDgDIgGgGQgEgCgEAAQgEAAgEACg");
	this.shape_94.setTransform(28.2,8.5);

	this.shape_95 = new cjs.Shape();
	this.shape_95.graphics.f("#FFFFFF").s().p("AgOAjQgGgDgEgGQgFgFgCgHQgCgHAAgHQAAgGACgHQACgHAFgFQAEgGAGgDQAGgDAIAAQAIAAAGADQAHADAEAGQAFAFABAHQADAHAAAGQAAAHgDAHQgBAHgFAFQgEAGgHADQgGADgIAAQgIAAgGgDgAgHgWQgEACgCAEIgEAIIgBAIIABAJIAEAJQACADAEACQADACAEAAQAFAAADgCQADgCADgDQACgEACgFIABgJIgBgIQgCgFgCgDIgGgGQgDgCgFAAQgEAAgDACg");
	this.shape_95.setTransform(20.4,8.5);

	this.shape_96 = new cjs.Shape();
	this.shape_96.graphics.f("#FFFFFF").s().p("AgOAjQgHgDgEgGQgEgFgCgHQgCgHAAgHQAAgGACgHQACgHAEgFQAEgGAHgDQAGgDAIAAQAJAAAGADQAGADAFAGQADAFACAHQADAHAAAGQAAAHgDAHQgCAHgDAFQgFAGgGADQgGADgJAAQgIAAgGgDgAgIgWQgDACgCAEIgEAIIgBAIIABAJIAEAJQACADADACQAEACAEAAQAEAAAEgCQAEgCACgDQACgEACgFIAAgJIAAgIQgCgFgCgDIgGgGQgEgCgEAAQgEAAgEACg");
	this.shape_96.setTransform(12.6,8.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_96},{t:this.shape_95},{t:this.shape_94},{t:this.shape_93},{t:this.shape_92},{t:this.shape_91},{t:this.shape_90},{t:this.shape_89},{t:this.shape_88},{t:this.shape_87},{t:this.shape_86},{t:this.shape_85},{t:this.shape_84},{t:this.shape_83},{t:this.shape_82},{t:this.shape_81},{t:this.shape_80},{t:this.shape_79},{t:this.shape_78},{t:this.shape_77},{t:this.shape_76},{t:this.shape_75},{t:this.shape_74},{t:this.shape_73},{t:this.shape_72},{t:this.shape_71},{t:this.shape_70},{t:this.shape_69},{t:this.shape_68},{t:this.shape_67},{t:this.shape_66},{t:this.shape_65},{t:this.shape_64},{t:this.shape_63},{t:this.shape_62},{t:this.shape_61},{t:this.shape_60},{t:this.shape_59},{t:this.shape_58},{t:this.shape_57},{t:this.shape_56},{t:this.shape_55},{t:this.shape_54},{t:this.shape_53},{t:this.shape_52},{t:this.shape_51},{t:this.shape_50},{t:this.shape_49},{t:this.shape_48},{t:this.shape_47},{t:this.shape_46},{t:this.shape_45},{t:this.shape_44},{t:this.shape_43},{t:this.shape_42},{t:this.shape_41},{t:this.shape_40},{t:this.shape_39},{t:this.shape_38},{t:this.shape_37},{t:this.shape_36},{t:this.shape_35},{t:this.shape_34},{t:this.shape_33},{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,225,37.5);


(lib.Символ14 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AMTAxQgDgCAAgGQAAgFADgDQADgDAGAAQAFAAADADQADADAAAFQAAAGgDACQgDAEgFAAQgGAAgDgEgALPAvQgJgFgHgIIARgOQAEAHAGADQAFAEAHAAIAHgBIAFgDIADgEIABgGQAAgDgCgCIgFgEIgGgCIgIgDIgLgEIgJgEQgEgEgDgEQgCgFAAgIQAAgFACgGQADgFAEgEQAFgEAGgDQAGgCAIAAIALABIAJADIAHAFIAHAHIgQALQgGgJgMAAQgHAAgEACQgEAEAAAFQAAADACACQACACADACIAGACIAIAEIALADQAFACAEADQAFAEACAFQADAFAAAGQAAAHgDAFQgCAGgEAFQgFAEgGACQgHAEgIAAQgOAAgKgGgAJ5AwQgKgEgHgHQgHgHgDgKQgEgJAAgLQAAgLAEgJQAEgKAHgGQAHgIAKgEQAJgEALAAQAIABAGABQAHACAGAEQAFACAFAGIAIAKIgRAKQgEgIgHgEQgHgFgKAAQgHAAgGADQgGACgFAFQgEAFgDAFQgCAHAAAGQAAAHACAGQADAGAEAEQAFAFAGADQAGADAHAAQALAAAHgGQAHgFAEgJIASAJQgEAHgFAFQgEAFgGAFIgNAFQgHADgIAAQgLAAgKgFgAGLAwQgKgEgHgHQgHgHgEgKQgEgJAAgLQAAgKAEgJQAEgKAHgHQAHgHAKgFQAJgEALAAQALAAAJAEQAKAFAHAHQAHAHAEAKQAEAJAAAKQAAALgEAJQgEAKgHAHQgHAHgKAEQgJAFgLAAQgLAAgJgFgAGSgeQgGACgFAFQgEAFgDAFQgCAHAAAGQAAAHACAGQADAGAEAFQAFAEAGADQAGADAHAAQAHAAAGgDQAGgDAFgEQAEgFADgGQACgGAAgHQAAgGgCgHQgDgFgEgFQgFgFgGgCQgGgDgHAAQgHAAgGADgAB/AwQgJgEgHgHQgHgHgEgKQgEgJAAgLQAAgLAEgJQAEgKAIgGQAHgIAJgEQAKgEALAAQAHABAHABQAGACAGAEQAGACAFAGIAIAKIgRAKQgFgIgGgEQgHgFgKAAQgHAAgHADQgGACgEAFQgFAFgCAFQgDAHAAAGQAAAHADAGQACAGAFAEQAEAFAGADQAGADAHAAQALAAAHgGQAIgFAEgJIARAJQgDAHgFAFQgFAFgGAFIgNAFQgHADgHAAQgMAAgKgFgAjhAwQgKgEgHgHQgHgIgEgJQgEgKAAgKQAAgKAEgJQAEgKAHgHQAHgHAKgFQAJgEAMAAQAIAAAHACQAHACAGAEQAFADAFAFIAIALIgRAJQgEgIgIgEQgHgFgKAAQgHAAgHACQgGAEgEAEQgFAFgCAFQgDAHAAAGQAAAHADAGQACAGAFAFQAEAEAHADQAGADAHAAQAMAAAIgGQAHgGADgKIghAAIAAgSIA1AAIAAAHQAAAKgDAKQgEAJgGAHQgHAHgJAEQgJAFgMAAQgMAAgJgFgAmdAyQgHgCgFgFQgFgEgDgIQgDgGAAgJIAAhCIAUAAIAABDIABAHIAEAFQACADADACIAHABIAHgBIAGgFIAEgFIABgHIAAhDIATAAIAABCQAAAJgDAGQgCAIgFAEQgFAFgHACQgHADgIAAQgIAAgGgDgAn3AvQgKgFgHgIIASgOQADAHAGADQAGAEAHAAIAHgBIAEgDIAEgEIAAgGQAAgDgBgCIgFgEIgHgCIgIgDIgKgEIgJgEQgFgEgCgEQgDgFAAgIQAAgFADgGQACgFAFgEQAEgEAHgDQAGgCAHAAIALABIAJADIAIAFIAGAHIgPALQgHgJgMAAQgHAAgDACQgEAEAAAFQAAADACACQABACADACIAHACIAIAEIAKADQAFACAFADQAEAEADAFQACAFAAAGQAAAHgCAFQgCAGgFAFQgEAEgHACQgHAEgIAAQgOAAgJgGgAsWAvQgJgFgHgIIARgOQAEAHAGADQAFAEAHAAIAHgBIAFgDIADgEIABgGQAAgDgCgCIgFgEIgGgCIgIgDIgLgEIgJgEQgEgEgDgEQgCgFAAgIQAAgFACgGQADgFAEgEQAFgEAGgDQAGgCAIAAIALABIAJADIAHAFIAHAHIgQALQgGgJgMAAQgHAAgEACQgEAEAAAFQAAADACACQACACADACIAGACIAIAEIALADQAFACAEADQAFAEACAFQADAFAAAGQAAAHgDAFQgCAGgEAFQgFAEgGACQgHAEgIAAQgOAAgKgGgAI9AzIAAhlIATAAIAABlgAIdAzIguhHIAABHIgTAAIAAhlIAWAAIAsBFIAAhFIATAAIAABlgAFQAzIgQgfIgRAAIAAAfIgTAAIAAhlIAgAAQAJAAAIACQAHADAFAEQAEAGADAGQADAHAAAHQAAAJgFAIQgEAIgJAEIAVAlgAEvACIAMAAQAGABAEgCQAEgBACgDIADgFQACgEAAgEQAAgHgFgFQgFgEgLgBIgMAAgADkAzIAAhTIgcAAIAAgSIBKAAIAAASIgbAAIAABTgAAcAzIAAhlIA8AAIAAASIgpAAIAAAYIApAAIAAARIgpAAIAAAYIApAAIAAASgAgnAzIAAhlIATAAIAABTIAlAAIAAASgAhuAzIAAhlIA8AAIAAASIgpAAIAAAYIApAAIAAARIgpAAIAAAYIApAAIAAASgAkeAzIgthHIAABHIgTAAIAAhlIAVAAIAsBFIAAhFIATAAIAABlgAohAzIAAhGIgfAoIgfgoIAABGIgTAAIAAhlIATAAIAfArIAggrIASAAIAABlgAqOAzIgGgSIgnAAIgHASIgUAAIAlhlIATAAIAkBlgAq1AOIAbAAIgOglgAMXAXIgCgNIgBgOIgBgPIgBgPIAAgQIATAAIAAAQIAAAPIgBAPIgBAOIgCANg");
	this.shape.setTransform(80.7,5.3);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,161.5,10.5);


(lib.Символ13 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AJzBbQgQgFgMgMQgNgKgIgPQgIgOgDgSIgXAAIAABOIgjAAIAAi9IAjAAIAABOIAXAAQADgSAIgOQAIgPANgKQAMgLAQgGQAQgGARgBQAUABARAHQASAIAMANQANANAIASQAHASAAATQAAAVgHARQgIASgMAOQgNANgRAHQgSAIgUAAQgSgBgPgGgAJ9g5QgLAFgIAJQgIAHgEAMQgFAMAAAMQAAANAFAMQAEAMAIAIQAIAIALAFQALAFAMAAQANAAALgFQALgFAIgIQAIgIAEgMQAFgMAAgNQAAgMgFgMQgEgLgIgIQgIgJgLgFQgLgEgNAAQgMAAgLAEgAliBdQgMgFgIgHQgIgJgFgLQgEgMAAgNIAAhFQAAgNAFgMQAFgMAIgIQAJgJAMgEQALgGAPAAQAPAAALAGQAMAEAJAJQAIAIAFAMQAEAMAAANIAABFQAAAOgEALQgFALgIAJQgIAIgMAEQgMAFgPAAQgQAAgMgFgAlcg1QgHAJAAAMIAABCQAAAMAHAJQAHAHAOABQAPAAAHgJQAIgIAAgLIAAhDQAAgOgIgHQgHgJgOABQgOAAgIAIgAnwBeQgKgCgIgGQgIgFgGgGQgGgHgEgHIAhgTQAEAJAIAHQAIAHAMAAQAGAAAFgCQAGgDAEgDQAEgEACgGQACgFAAgHQAAgNgIgJQgIgKgOAAQgLABgHAFQgHAGgFAIIgggQIAOhlIBqAAIAAAhIhOAAIgFArQAFgEAIgDQAHgCAJAAQANAAALADQALAFAJAIQAIAIAFALQAFALAAAQQAAAOgFAMQgFALgIAJQgJAHgMAFQgMAFgOAAQgMAAgLgEgAHDBfIAAiEIhOCEIglAAIAAi9IAjAAIAACCIBMiCIAoAAIAAC9gADoBfIAAibIgzAAIAAgiICJAAIAAAiIgzAAIAACbgAA1BfIAAi9IBwAAIAAAiIhNAAIAAAsIBNAAIAAAhIhNAAIAAAsIBNAAIAAAigAABBfIgviKIgwCKIglAAIBDi9IAkAAIBCC9gAqMBfIg2hOIgMAAIAABOIgkAAIAAi9IAkAAIAABOIALAAIA3hOIAoAAIhCBdIBFBggAjwAsIAAgeIBgAAIAAAeg");
	this.shape.setTransform(75.5,9.8);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,151,19.5);


(lib.Символ12 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.rf(["#FFFFFF","rgba(255,255,255,0)"],[0,1],0,0,0,0,0,142.7).s().p("AvnPpQmfmfAApKQAApJGfmeQGemfJJAAQJKAAGfGfQGeGeAAJJQAAJKmeGfQmfGepKAAQpJAAmemeg");
	this.shape.setTransform(141.5,141.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,283,283);


(lib.Символ11 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgIA0QgDgDAAgGQAAgFADgEQADgDAFAAQAGAAADADQADAEAAAFQAAAGgDADQgEAEgFAAQgFAAgDgEgAgFAYIgBgOIgCgPIgBgQIAAgQIAAgSIATAAIAAASIAAAQIgBAQIgCAPIgCAOg");
	this.shape.setTransform(95.3,36.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgRArQgIgEgHgFQgFgGgFgJQgDgIAAgLQAAgKADgIQAFgJAFgGQAGgGAJgDQAHgDAJAAQAHAAAHADQAIAEAFAFIAAgKIAUAAIAABXIgUAAIAAgMQgFAHgIADQgHAEgIAAQgIAAgHgDgAgJgYQgFACgDADQgEAEgCAFQgCAFAAAFQAAAFACAFQACAFAEAEQADAEAFACQAFACAFAAQAFAAAFgCQAFgCADgEIAGgJQABgFABgFQgBgFgBgFIgGgIQgDgEgFgCQgFgCgFAAQgFAAgFACg");
	this.shape_1.setTransform(88.6,37.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgtBBIAAh/IAUAAIAAALQAFgGAHgEQAIgDAIAAQAIAAAIADQAIADAGAGQAGAGADAJQAEAHAAAMQAAALgEAHQgEAIgGAHQgGAFgIAEQgHADgIAAQgIgBgIgDQgHgDgFgGIAAAzgAgKgsQgFACgDAFQgEADgCAFQgCAFAAAGQAAAFACAFQACAFAEADQADADAFADQAFACAFAAQAFAAAFgCQAFgDADgDQAEgDACgFQACgFAAgFQAAgHgCgEQgCgFgEgEQgDgDgFgDQgFgBgFAAQgFAAgFABg");
	this.shape_2.setTransform(78.9,39.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgRAqQgIgEgGgGQgGgGgEgIQgEgJAAgJQAAgJAEgIQAEgIAGgGQAGgHAIgDQAJgEAIAAQAKAAAHAEQAJADAGAHQAGAGAEAIQAEAIAAAJQAAAJgEAJQgEAIgGAGQgGAGgJAEQgHAEgKAAQgIAAgJgEgAgJgYQgFACgEAEQgDAEgBAFQgCAEAAAFQAAAFACAFQABAFADAEQAEADAFACQAFACAEAAQAFAAAFgCQAEgCAEgDQADgEACgFQACgFAAgFQAAgFgCgEQgCgFgDgEQgEgEgEgCQgFgCgFAAQgEAAgFACg");
	this.shape_3.setTransform(68.9,37.2);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgUAqQgJgEgHgIIAOgNQAFAFAGADQAGACAGAAQAHAAAFgDQAEgCAAgFQAAgEgEgDQgFgCgIAAIgMAAIAAgQIAMAAQAHAAAEgDQAEgCAAgFQAAgEgEgCQgDgDgIAAQgFAAgGADQgFACgEAFIgPgMQAHgIAJgEQAJgEALAAQAHAAAHACQAGACAFADQAEADADAFQACAFAAAFQAAAHgDAFQgDAEgFADQAGACAEAFQADAFAAAIQAAAFgCAFQgDAFgEAEQgFADgHACQgHADgIAAQgMAAgJgEg");
	this.shape_4.setTransform(60,37.2);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAUAsIAAg5IgnA5IgUAAIAAhXIAUAAIAAA4IAmg4IAVAAIAABXg");
	this.shape_5.setTransform(51.5,37.2);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgkAsIAAhXIAnAAQAOAAAJAGQAIAGAAAMQABAMgLAGQANAFAAAOQAAANgJAGQgIAHgQAAgAgRAbIAVAAQAGAAAEgDQADgCgBgFQABgFgDgCQgEgDgGAAIgVAAgAgRgJIAVAAQAFAAACgCQAEgCAAgFQAAgEgEgCQgCgCgFAAIgVAAg");
	this.shape_6.setTransform(42.9,37.2);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgRAqQgJgEgFgGQgHgGgDgIQgEgIAAgKQAAgIAEgJQAEgIAGgGQAGgHAIgDQAJgEAIAAQAKAAAIAEQAJADAFAGQAGAGAEAIQAEAJAAAJIAAAHIhHAAQACAJAHAGQAHAGAKAAQAJAAAFgEQAHgFADgHIARAKQgGALgKAGQgLAHgOAAQgJAAgJgEgAgPgWQgHAFgCAIIAwAAQgCgJgGgEQgHgFgJAAQgIAAgHAFg");
	this.shape_7.setTransform(33.8,37.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AAYAsIgYg8IgXA8IgVAAIAkhXIARAAIAkBXg");
	this.shape_8.setTransform(24.3,37.2);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgRAqQgJgEgFgGQgHgGgDgIQgEgIAAgKQAAgIAEgJQADgIAHgGQAGgHAIgDQAJgEAIAAQAKAAAIAEQAJADAGAGQAFAGAEAIQADAJAAAJIAAAHIhGAAQACAJAHAGQAHAGAKAAQAJAAAFgEQAHgFADgHIARAKQgGALgKAGQgLAHgOAAQgJAAgJgEgAgPgWQgGAFgDAIIAwAAQgCgJgGgEQgGgFgKAAQgIAAgHAFg");
	this.shape_9.setTransform(14.8,37.2);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgJAsIAAhEIgcAAIAAgTIBLAAIAAATIgcAAIAABEg");
	this.shape_10.setTransform(6,37.2);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAUAsIAAg5IgnA5IgUAAIAAhXIAUAAIAAA4IAmg4IAVAAIAABXg");
	this.shape_11.setTransform(187.9,18.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgJAsIAAhEIgcAAIAAgTIBLAAIAAATIgcAAIAABEg");
	this.shape_12.setTransform(179.4,18.5);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgPAqQgIgEgHgGQgGgGgDgIQgEgJAAgJQAAgJAEgIQADgIAGgGQAHgHAIgDQAIgEAJAAQAHAAAHACQAGACAGAEQAFADAEAFQAEAFADAGIgSAIQgDgHgHgEQgGgFgIAAQgFAAgEACQgFACgEAEQgDAEgCAFQgCAEAAAFQAAAFACAFQACAFADAEQAEADAFACQAEACAFAAQAJAAAGgEQAGgFADgHIASAIQgDAGgEAFQgEAFgFAEIgMAGQgGACgIAAQgJAAgIgEg");
	this.shape_13.setTransform(170.9,18.5);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AgRAqQgIgEgGgGQgHgGgDgIQgDgJgBgJQABgJADgIQADgIAHgGQAGgHAIgDQAIgEAJAAQAJAAAIAEQAJADAGAHQAHAGADAIQAEAIgBAJQABAJgEAJQgDAIgHAGQgGAGgJAEQgIAEgJAAQgJAAgIgEgAgJgYQgFACgEAEQgCAEgCAFQgCAEgBAFQABAFACAFQACAFACAEQAEADAFACQAEACAFAAQAGAAAEgCQAFgCADgDQAEgEACgFQABgFAAgFQAAgFgBgEQgCgFgEgEQgDgEgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_14.setTransform(161.4,18.5);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AAcAsIAAg5IgcAfIgbgeIAAA4IgUAAIAAhXIATAAIAcAjIAegjIASAAIAABXg");
	this.shape_15.setTransform(151.2,18.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AAUAsIAAg5IgnA5IgUAAIAAhXIAUAAIAAA4IAmg4IAVAAIAABXg");
	this.shape_16.setTransform(141.3,18.5);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AgRAqQgIgEgGgGQgGgGgEgIQgEgJAAgJQAAgJAEgIQAEgIAGgGQAGgHAIgDQAJgEAIAAQAKAAAHAEQAJADAGAHQAGAGAEAIQAEAIAAAJQAAAJgEAJQgEAIgGAGQgGAGgJAEQgHAEgKAAQgIAAgJgEgAgJgYQgFACgEAEQgDAEgBAFQgCAEAAAFQAAAFACAFQABAFADAEQAEADAFACQAFACAEAAQAFAAAFgCQAEgCAEgDQADgEACgFQACgFAAgFQAAgFgCgEQgCgFgDgEQgEgEgEgCQgFgCgFAAQgEAAgFACg");
	this.shape_17.setTransform(131.9,18.5);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgJAsIAAhEIgcAAIAAgTIBLAAIAAATIgcAAIAABEg");
	this.shape_18.setTransform(123.1,18.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgPAqQgIgEgHgGQgGgGgDgIQgEgJAAgJQAAgJAEgIQADgIAGgGQAHgHAIgDQAIgEAJAAQAHAAAHACQAGACAGAEQAFADAEAFQAEAFADAGIgSAIQgDgHgHgEQgGgFgIAAQgFAAgEACQgFACgEAEQgDAEgCAFQgCAEAAAFQAAAFACAFQACAFADAEQAEADAFACQAEACAFAAQAJAAAGgEQAGgFADgHIASAIQgDAGgEAFQgEAFgFAEIgMAGQgGACgIAAQgJAAgIgEg");
	this.shape_19.setTransform(114.5,18.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AgJAsIAAhEIgcAAIAAgTIBLAAIAAATIgcAAIAABEg");
	this.shape_20.setTransform(102.2,18.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AgRAqQgIgEgGgGQgHgGgDgIQgDgJgBgJQABgJADgIQADgIAHgGQAGgHAIgDQAIgEAJAAQAJAAAIAEQAJADAGAHQAHAGADAIQAEAIgBAJQABAJgEAJQgDAIgHAGQgGAGgJAEQgIAEgJAAQgJAAgIgEgAgJgYQgFACgEAEQgCAEgCAFQgCAEgBAFQABAFACAFQACAFACAEQAEADAFACQAEACAFAAQAGAAAEgCQAFgCADgDQAEgEACgFQABgFAAgFQAAgFgBgEQgCgFgEgEQgDgEgFgCQgEgCgGAAQgFAAgEACg");
	this.shape_21.setTransform(93.4,18.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FF9900").s().p("AAfBQQgHgEgFgFQgFgFgEgHQgDgIAAgIQAAgIADgHQAEgHAFgFQAFgGAHgDQAIgDAIAAQAIAAAHADQAHADAFAGQAGAFADAHQADAHAAAIQAAAIgDAIQgDAHgGAFQgFAFgHAEQgHADgIAAQgIAAgIgDgAAlAhQgFAFAAAFQAAAGAFAEQAEAFAGAAQAFAAAFgFQAEgEAAgGQAAgFgEgFQgFgEgFAAQgGAAgEAEgAhXBQICJifIAmAAIiJCfgAg9gGQgHgDgFgGQgGgFgDgHQgDgHAAgIQAAgJADgHQADgHAGgFQAFgFAHgDQAHgEAJAAQAIAAAHAEQAHADAFAFQAFAFAEAHQADAHAAAJQAAAIgDAHQgEAHgFAFQgFAGgHADQgHADgIAAQgJAAgHgDgAg4g0QgEAEAAAGQAAAGAEAEQAFAEAGAAQAFAAAEgEQAFgEAAgGQAAgGgFgEQgEgFgFAAQgGAAgFAFg");
	this.shape_22.setTransform(75.1,14.9);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FF9900").s().p("AgWBPQgKgEgIgHQgGgHgEgKQgDgJAAgLIAAg7QAAgLAEgKQADgJAIgIQAHgHAKgEQAKgFALAAQAMAAAKAFQALAEAHAHQAHAIAEAJQAEAKAAALIAAA7QAAAMgEAJQgEAJgHAHQgHAHgKAEQgKAEgNAAQgMAAgKgEgAgRgtQgGAIAAAKIAAA4QgBAKAHAIQAGAGALAAQAMAAAHgHQAGgHAAgJIAAg5QAAgLgGgHQgHgHgLAAQgLAAgHAHg");
	this.shape_23.setTransform(59.5,14.9);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FF9900").s().p("AgSBPQgJgDgHgEQgHgEgFgGQgFgFgDgGIAcgQQAEAHAGAGQAHAGAJAAQAFAAAFgCQAEgCAEgDQADgDACgFQACgFAAgFQAAgMgHgHQgGgIgMAAQgJAAgGAFQgGAEgEAHIgbgNIALhVIBZAAIAAAcIhAAAIgGAjIAMgFQAGgCAHAAQAKAAAKADQAKAEAGAHQAIAGADAJQAFAKAAAOQAAALgEAKQgEAKgIAHQgHAHgKAEQgKADgMAAQgJAAgJgCg");
	this.shape_24.setTransform(47.1,15);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FF9900").s().p("AgfBMQgPgGgLgMQgLgLgHgPQgGgPAAgRQAAgQAGgPQAHgPALgLQALgMAPgGQAOgHARAAQARAAAPAHQAPAGALAMQAMALAGAPQAGAPAAAQQAAARgGAPQgGAPgMALQgLAMgPAGQgPAHgRAAQgRAAgOgHgAgTgwQgLAEgGAHQgIAIgDAJQgFAKAAAKQAAALAFAKQADAJAIAIQAGAHALAEQAJAEAKAAQALAAAJgEQAKgEAHgHQAHgIAEgJQAFgKAAgLQAAgKgFgKQgEgJgHgIQgHgHgKgEQgJgEgLAAQgKAAgJAEg");
	this.shape_25.setTransform(27.1,14.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FF9900").s().p("AA0BfIAAgeIhmAAIAAAeIgdAAIAAg6IARAAIAwiDIAeAAIAvCDIAQAAIAAA6gAgfAlIBAAAIghhbg");
	this.shape_26.setTransform(10.2,16.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,194.7,47.9);


(lib.Символ10 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgVA8IATgrIglhMIAJAAIAfBDIAehDIAJAAIg1B3g");
	this.shape.setTransform(183.1,34.7);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AAXApIgiglIgNAAIAAAlIgIAAIAAhRIAIAAIAAAlIAMAAIAiglIAKAAIglAoIAmApg");
	this.shape_1.setTransform(174.9,32.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AAcApIAAhJIg3AAIAABJIgHAAIAAhRIBFAAIAABRg");
	this.shape_2.setTransform(165.6,32.8);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AgVA8IATgrIglhMIAJAAIAfBDIAehDIAJAAIg1B3g");
	this.shape_3.setTransform(156.3,34.7);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AAXApIgjglIgMAAIAAAlIgIAAIAAhRIAIAAIAAAlIAMAAIAiglIAJAAIgkAoIAmApg");
	this.shape_4.setTransform(148.1,32.8);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgQAoQgIgEgGgFQgFgHgDgHQgDgIAAgJQAAgIADgHQADgJAFgFQAGgGAIgEQAIgCAIAAQAJAAAHACQAIAEAGAGQAGAFADAJQADAHAAAIQAAAJgDAIQgDAHgGAHQgGAFgIAEQgHACgJAAQgIAAgIgCgAgMgfQgHADgEAEQgFAFgDAHQgCAGAAAGQAAAHACAHQADAGAFAFQAEAFAHADQAFACAHAAQAHAAAHgCQAFgDAFgFQAFgFADgGQACgHAAgHQAAgGgCgGQgDgHgFgFQgFgEgFgDQgHgDgHAAQgHAAgFADg");
	this.shape_5.setTransform(138.5,32.8);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AAbApIAAhJIg1AAIAABJIgJAAIAAhRIBHAAIAABRg");
	this.shape_6.setTransform(128.7,32.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgEAoQgGgDgGgFQgGgGgDgHQgEgHAAgIIgPAAIAAAlIgIAAIAAhRIAIAAIAAAlIAPAAQABgIADgHQADgHAGgFQAGgFAGgEQAHgCAIAAQAJAAAIACQAHAEAFAGQAGAFADAJQAEAHAAAIQAAAJgEAIQgDAHgGAHQgFAFgHAEQgIACgJAAQgIAAgHgCgAgBgfQgGADgEAEQgFAFgCAHQgDAGAAAGQAAAHADAHQACAGAFAFQAEAFAGADQAFACAHAAQAHAAAHgCQAFgDAFgFQAEgFADgGQADgHAAgHQAAgGgDgGQgDgHgEgFQgFgEgFgDQgHgDgHAAQgHAAgFADg");
	this.shape_7.setTransform(114.3,32.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgVA8IATgrIglhMIAJAAIAfBDIAehDIAJAAIg1B3g");
	this.shape_8.setTransform(103.2,34.7);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AA0AyIAAgSIhuAAIAAhRIAIAAIAABKIAqAAIAAhKIAIAAIAABKIApAAIAAhKIAIAAIAABKIAKAAIAAAZg");
	this.shape_9.setTransform(92.5,33.7);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AgEAoQgGgDgGgFQgGgGgDgHQgDgHgBgIIgOAAIAAAlIgIAAIAAhRIAIAAIAAAlIAOAAQABgIADgHQADgHAGgFQAGgFAGgEQAHgCAIAAQAJAAAIACQAHAEAFAGQAGAFADAJQADAHAAAIQAAAJgDAIQgDAHgGAHQgFAFgHAEQgIACgJAAQgIAAgHgCgAgBgfQgGADgFAEQgEAFgDAHQgCAGAAAGQAAAHACAHQADAGAEAFQAFAFAGADQAFACAHAAQAIAAAFgCQAHgDAEgFQAEgFACgGQADgHABgHQgBgGgDgGQgCgHgEgFQgEgEgHgDQgFgDgIAAQgHAAgFADg");
	this.shape_10.setTransform(79.3,32.8);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgVA8IATgrIglhMIAJAAIAfBDIAehDIAJAAIg1B3g");
	this.shape_11.setTransform(68.3,34.7);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AAlAyIAAgSIhJAAIAAASIgIAAIAAgZIAHAAIAihKIAIAAIAhBKIAGAAIAAAZgAgcAZIA5AAIgdhBg");
	this.shape_12.setTransform(59.1,33.7);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("AgQAoQgIgEgFgFQgHgHgCgHQgDgIAAgJQAAgHADgIQADgJAGgFQAGgGAHgEQAIgCAIAAQAKAAAHACQAHADAGAGQAGAGADAHQADAIAAAJIAAADIhMAAQABAHACAGQADAGAFAEQAFAEAGADQAGACAHAAQALAAAIgFQAJgGAEgKIAHADQgGAMgJAHQgJAGgPAAQgJAAgIgCgAgLggQgHACgEAEQgEAFgDAFQgEAGAAAHIBDAAQgBgIgDgFQgCgFgEgFQgFgEgGgCQgFgDgIAAQgGAAgFADg");
	this.shape_13.setTransform(49.5,32.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AAgApIgghHIgfBHIgJAAIAlhRIAHAAIAlBRg");
	this.shape_14.setTransform(39.9,32.8);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgOAoQgIgEgGgGQgFgFgEgJQgDgHAAgJQAAgIADgIQAEgIAFgFQAGgGAIgEQAIgCAIAAQAGAAAGABQAGACAGADQAFAEADAEQAEAFADAFIgIAEQgEgKgIgGQgIgFgLAAQgHAAgGADQgGADgFAEQgFAFgCAHQgDAGAAAGQAAAHADAHQACAGAFAFQAFAFAGADQAHACAGAAQALABAIgHQAIgGAEgJIAIADQgCAFgEAFQgEAFgFADQgFAEgGACQgGACgHgBQgIAAgIgCg");
	this.shape_15.setTransform(30.5,32.8);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#FFFFFF").s().p("AgQAoQgHgEgGgGQgGgFgDgJQgDgHAAgJQAAgIADgHQADgIAGgGQAGgGAHgEQAIgCAIAAIAKABQAFABAFADIAIAGQAEAEADAFIAAgTIAHAAIAABRIgHAAIAAgSIgHAIQgEAEgEADIgKADIgKABQgIAAgIgCgAgMgfQgGADgFAEQgFAFgDAHQgCAGAAAGQAAAHACAHQADAGAFAFQAFAFAGADQAGACAGAAQAIAAAGgCQAGgDAFgFQAFgFADgGQACgHAAgHQAAgGgCgGQgDgHgFgFQgFgEgGgDQgGgDgIAAQgGAAgGADg");
	this.shape_16.setTransform(16.6,32.8);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("AAcApIAAglIg3AAIAAAlIgIAAIAAhRIAIAAIAAAlIA3AAIAAglIAIAAIAABRg");
	this.shape_17.setTransform(6.8,32.8);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("AgMA4IAAhXIgjAAIAAgYIBfAAIAAAYIgjAAIAABXg");
	this.shape_18.setTransform(184.8,14.5);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("AgXA2QgJgEgIgIQgIgHgFgLQgEgKAAgOQAAgNAEgKQAFgMAIgGQAIgIAJgEQAKgEALAAQAKAAAJAEQAJAEAHAIIAAgOIAZAAIAABvIgZAAIAAgPQgHAIgJAFQgKAEgJAAQgKAAgLgEgAgLgfQgHADgEAFQgFAEgCAGQgDAGAAAHQAAAHADAGQACAGAFAFQAEAFAHACQAFADAHAAQAHAAAGgDQAGgCAFgFQAEgFACgGQADgGAAgHQAAgGgDgHQgCgGgEgEQgFgFgGgDQgGgDgHABQgHgBgFADg");
	this.shape_19.setTransform(173.2,14.5);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("AAVA4IglgsIgKAAIAAAsIgZAAIAAhvIAZAAIAAAsIAIAAIAmgsIAeAAIgwA2IAzA5g");
	this.shape_20.setTransform(161.8,14.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#FFFFFF").s().p("AAZA4IAAhJIgxBJIgZAAIAAhvIAYAAIAABHIAxhHIAbAAIAABvg");
	this.shape_21.setTransform(150,14.5);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgMBhIAAgwQgMABgKgFQgLgEgIgIQgIgIgFgKQgEgKAAgLQAAgLAEgLQAFgKAIgHQAIgIALgFQAKgEAMAAIAAgiIAZAAIAAAiQAMAAALAEQALAFAIAIQAHAHAFAKQAEALAAALQAAALgEAKQgFAKgIAIQgIAIgKAEQgLAFgMgBIAAAwgAANAbQAHgBAGgDQAGgDAFgDQAEgFACgGQADgGAAgGQAAgHgDgGQgCgGgEgEQgFgEgGgDQgGgDgHgBgAgZgkQgGACgEAEQgFAFgCAGQgDAGAAAHQAAAGADAGQACAGAFAFQAEADAGADQAHADAGABIAAhDQgGABgHADg");
	this.shape_22.setTransform(136.8,15.2);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AAZA4IAAhJIgxBJIgZAAIAAhvIAZAAIAABHIAwhHIAaAAIAABvg");
	this.shape_23.setTransform(123.7,14.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgMA4IAAhXIgjAAIAAgYIBfAAIAAAYIgjAAIAABXg");
	this.shape_24.setTransform(112.8,14.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("Ag5BSIAAihIAaAAIAAAPQAFgIAKgFQAJgEALAAQAKAAAKAEQAKAEAHAHQAIAHAEALQAFALAAAOQAAANgFAKQgFALgHAHQgHAIgLAEQgKAEgJAAQgLAAgJgEQgKgEgFgIIAABAgAgNg3QgGADgEAEQgFAFgCAGQgDAGABAHQgBAIADAGQACAGAFAEQAEAFAGACQAHADAGAAQAGAAAHgDQAFgCAFgFQAFgEADgGQACgGAAgIQAAgHgCgGQgDgGgFgFQgFgEgFgDQgHgDgGAAQgGAAgHADg");
	this.shape_25.setTransform(101.7,16.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgWA2QgLgFgIgIQgHgIgFgKQgDgLAAgMQgBgLAFgLQAEgKAIgIQAIgIAKgEQALgFALAAQAMAAALAFQAKADAIAIQAIAIAEAKQAFALgBAMIAAAJIhZAAQACAMAKAHQAIAHANAAQALAAAIgFQAIgFAEgKIAVANQgHAOgNAHQgNAJgTAAQgMAAgLgEgAgTgcQgIAGgEAKIA+AAQgDgLgIgGQgIgFgMAAQgKgBgJAHg");
	this.shape_26.setTransform(89.1,14.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgUA1QgKgFgIgHQgIgIgEgLQgFgKABgMQgBgLAFgLQAEgKAIgIQAIgIAKgEQALgFALAAQAJAAAJACQAIADAHAFQAHAEAFAGQAFAHADAHIgXAKQgDgJgJgGQgIgFgJAAQgHAAgGADQgFADgFAEQgEAFgDAGQgDAGAAAGQAAAHADAGQADAGAEAFQAFAEAFADQAGACAHAAQAKABAIgGQAHgGAEgJIAYAKQgEAHgFAHQgFAHgHAEQgGAFgJACQgIADgKAAQgLAAgLgFg");
	this.shape_27.setTransform(77.2,14.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AAjA4IAAhIIgjAnIgignIAABIIgZAAIAAhvIAYAAIAjAsIAlgsIAXAAIAABvg");
	this.shape_28.setTransform(59.8,14.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AAZA4IAAhJIgxBJIgaAAIAAhvIAZAAIAABHIAxhHIAbAAIAABvg");
	this.shape_29.setTransform(47.3,14.5);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("Ag5BSIAAihIAZAAIAAAPQAHgIAJgFQAJgEAKAAQALAAAKAEQAKAEAHAHQAIAHAFALQAEALAAAOQAAANgEAKQgGALgHAHQgIAIgKAEQgJAEgLAAQgKAAgJgEQgJgEgHgIIAABAgAgNg3QgGADgFAEQgDAFgDAGQgCAGgBAHQABAIACAGQADAGADAEQAFAFAGACQAGADAHAAQAGAAAGgDQAHgCAEgFQAFgEACgGQADgGAAgIQAAgHgDgGQgCgGgFgFQgEgEgHgDQgGgDgGAAQgHAAgGADg");
	this.shape_30.setTransform(35.4,16.9);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgWA2QgKgEgIgIQgHgHgGgLQgEgKAAgOQAAgNAEgKQAFgMAIgGQAIgIAKgEQAJgEALAAQAKAAAJAEQAJAEAHAIIAAgOIAZAAIAABvIgZAAIAAgPQgHAIgJAFQgJAEgKAAQgLAAgJgEgAgLgfQgGADgFAFQgFAEgCAGQgDAGAAAHQAAAHADAGQACAGAFAFQAFAFAGACQAFADAGAAQAIAAAGgDQAGgCAEgFQAFgFADgGQACgGAAgHQAAgGgCgHQgDgGgFgEQgEgFgGgDQgGgDgIABQgGgBgFADg");
	this.shape_31.setTransform(22.3,14.5);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AAsBSIAAgaIhYAAIAAAaIgYAAIAAgyIAOAAIAphxIAaAAIAqBxIAOAAIAAAygAgbAgIA3AAIgchPg");
	this.shape_32.setTransform(9.1,14.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_32},{t:this.shape_31},{t:this.shape_30},{t:this.shape_29},{t:this.shape_28},{t:this.shape_27},{t:this.shape_26},{t:this.shape_25},{t:this.shape_24},{t:this.shape_23},{t:this.shape_22},{t:this.shape_21},{t:this.shape_20},{t:this.shape_19},{t:this.shape_18},{t:this.shape_17},{t:this.shape_16},{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,200,42.9);


(lib.Символ9 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("AgDAhIAAgcIgdAAIAAgIIAdAAIAAgdIAIAAIAAAdIAcAAIAAAIIgcAAIAAAcg");
	this.shape.setTransform(17.5,12.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AgRA/QgJgDgGgHQgGgGgEgIQgDgIAAgKQAAgJADgIQADgHAEgGIAng5IANAAIgfAtQAHgDAJAAQAJAAAIAEQAIADAGAGQAGAHAEAHQADAIAAAKQAAAKgDAIQgEAIgGAGQgGAHgJADQgIAEgKAAQgJAAgIgEgAgNgMQgHADgEAFQgFAEgDAHQgDAGAAAIQAAAHADAHQADAHAFAEQAEAFAHADQAHADAGAAQAIAAAGgDQAHgDAFgFQAEgEADgHQADgHAAgHQAAgIgDgGQgDgHgEgEQgFgFgHgDQgGgCgIAAQgGAAgHACg");
	this.shape_1.setTransform(7.5,12.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,24,26.3);


(lib.Символ6 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAYAmIAAgbIgYAAIgCAAIgCAAIgSAbIgIAAIASgdIgIgEIgFgFIgDgGIgBgHQAAgFACgFQACgEADgDQAEgDAFgCQAFgCAGAAIAhAAIAABLgAgKgdIgGAEIgFAFIgBAHQAAAEABADQACADADADIAGADQAEABAEAAIAaAAIAAgjIgaAAQgEABgEABg");
	this.shape.setTransform(117.9,10.6);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AgmA4IAAhuIAHAAIAAASQACgFAEgDIAHgGIAJgEIAJgBQAJAAAGADQAIADAFAFQAFAGADAHQADAHAAAIQAAAIgDAIQgDAGgFAFQgFAGgIADQgGADgJAAIgJgBIgJgEIgHgGIgGgIIAAA0gAgMguQgGADgEAEQgFAFgDAGQgBAFAAAHQAAAHABAGQADAFAFAEQAEAFAGACQAGADAGAAQAHAAAFgDQAGgCAEgFQAEgEADgFQACgGABgHQgBgHgCgFQgDgGgEgFQgEgEgGgDQgFgCgHAAQgGAAgGACg");
	this.shape_1.setTransform(109.4,12.2);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgPAuQgHgDgFgGQgFgGgCgIQgCgIAAgKQAAgKACgJQACgJAFgHQAFgHAIgEQAIgEALgBIAXgDIABAHIgYADIgMADQgFACgFAEQgEAEgDAHQgDAHgBAKQACgGADgDQADgDAFgDIAJgDIAIgBQAHAAAGACQAHADAFAEQAEAFADAHQADAFAAAIQAAAIgDAGQgDAIgEAEQgFAGgHACQgHADgIAAQgIAAgHgEgAgKgMQgFACgEADQgEAFgDAEQgCAFAAAHQAAAGACAFQADAGADAEQAEADAGADQAFACAFAAQAHAAAFgCQAFgDAEgDQAEgEACgGQACgGAAgGQAAgGgCgGQgCgDgDgFQgEgDgFgCQgGgDgGAAQgFAAgGADg");
	this.shape_2.setTransform(99.9,9.5);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AAYAmIAAgbIgYAAIgCAAIgCAAIgSAbIgIAAIASgdIgIgEIgFgFIgDgGIgBgHQAAgFACgFQACgEADgDQAEgDAFgCQAFgCAGAAIAhAAIAABLgAgKgdIgGAEIgFAFIgBAHQAAAEABADQACADADADIAGADQAEABAEAAIAaAAIAAgjIgaAAQgEABgEABg");
	this.shape_3.setTransform(91.1,10.6);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AgDAmIAAhFIgdAAIAAgGIBBAAIAAAGIgdAAIAABFg");
	this.shape_4.setTransform(83.7,10.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AAVAmIgggjIgLAAIAAAjIgIAAIAAhLIAIAAIAAAiIALAAIAfgiIAJAAIgiAlIAkAmg");
	this.shape_5.setTransform(76.6,10.6);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgOAlQgHgDgGgGQgFgFgDgIQgEgGAAgJQAAgHAEgIQADgGAFgGQAGgFAHgDQAHgEAHAAQAJAAAGAEQAIADAFAFQAGAGADAGQACAIAAAHQAAAJgCAGQgDAIgGAFQgFAGgIADQgGACgJAAQgHAAgHgCgAgMgdQgFACgFAFQgEAFgDAFQgCAGAAAGQAAAHACAGQADAGAEAEQAFAEAFADQAHACAFAAQAHAAAFgCQAGgDAFgEQAEgEADgGQACgGAAgHQAAgGgCgGQgDgFgEgFQgFgFgGgCQgFgCgHgBQgFABgHACg");
	this.shape_6.setTransform(67.7,10.6);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AgMAuQgFgCgEgDQgEgEgCgFQgCgFAAgGQAAgIAFgHQAEgGAHgCQgFgDgEgGQgEgFABgHQAAgGABgEQADgFADgDQADgDAGgCQAEgCAFAAQAGAAAFACQAEACAEADQAEADACAFQACAEAAAGQAAAHgEAFQgDAGgHADIAHADIAGAFIADAHIABAIQAAAGgCAFQgCAFgEAEQgEADgFACQgGADgHAAQgGAAgGgDgAgIACIgHAEQgDADgCAEQgBAEgBAEQABAEABAEQACAEADADIAHAEQAEACAEAAQAFAAAFgCIAHgEIAEgHQACgEAAgEQAAgEgCgEIgEgHIgHgEQgFgCgFAAQgEAAgEACgAgHgoQgDABgDADIgEAGQgBADAAAEIABAHIAEAFIAGAEQAEACADAAQAFAAADgCQAEgBACgDQADgCABgDIACgHIgBgHIgFgGQgCgDgDgBQgEgBgFAAQgDAAgEABg");
	this.shape_7.setTransform(56,9.6);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgdAwIAAgIQAAgFACgFIAGgJIAJgIIAKgHIAIgGIAIgGQADgEADgEQACgDAAgFQAAgIgHgFQgFgFgKAAQgHAAgGAEQgHAEgDAHIgGgEQAEgIAHgFQAIgFAKAAQAHAAAFACQAGACADADQAEAEACAEQACAFAAAGQAAAFgCAFIgGAIIgIAHIgKAHIgIAHIgIAGQgEAEgCAEQgCAEAAAEIAAABIA0AAIAAAHg");
	this.shape_8.setTransform(48.5,9.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgOAlQgIgDgFgGQgFgFgEgIQgCgGAAgJQAAgHACgIQAEgGAFgGQAFgFAIgDQAHgEAHAAQAIAAAIAEQAHADAFAFQAFAGADAGQADAIABAHQgBAJgDAGQgDAIgFAFQgFAGgHADQgIACgIAAQgHAAgHgCgAgLgdQgGACgEAFQgFAFgCAFQgDAGAAAGQAAAHADAGQACAGAFAEQAEAEAGADQAFACAGAAQAHAAAGgCQAGgDAEgEQAEgEACgGQADgGAAgHQAAgGgDgGQgCgFgEgFQgEgFgGgCQgGgCgHgBQgGABgFACg");
	this.shape_9.setTransform(36.6,10.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("AAaAmIAAhFIgzAAIAABFIgHAAIAAhLIBBAAIAABLg");
	this.shape_10.setTransform(27.5,10.6);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AAFAvIAAhWIgQAAIAAgHIAXAAIAABdg");
	this.shape_11.setTransform(17.2,9.6);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AgPAtQgJgEgHgHQgHgGgDgJQgEgJAAgKQAAgJAEgJQADgJAHgHQAHgGAJgEQAIgEAKAAQAGAAAGACIAMAFQAGADAEAEIAIAKIgHAEQgFgKgKgFQgJgGgLAAQgIAAgIADQgHAEgFAFQgGAGgDAIQgEAHAAAIQAAAIAEAIQADAIAGAFQAFAGAHADQAIADAIAAQAMAAAJgGQAKgGAFgJIAHADIgHAKQgFAFgFAEIgNAFQgGACgHAAQgKAAgIgEg");
	this.shape_12.setTransform(7.3,9.6);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_12},{t:this.shape_11},{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6},{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1},{t:this.shape}]}).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ6, new cjs.Rectangle(0,0,124.3,20.1), null);


(lib.Символ4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.lf(["#131313","#2C2C2C"],[0,1],16,152.2,-17.6,-167).s().p("AyvZPMAAAgydMAlfAAAMAAAAydg");
	this.shape.setTransform(120,161.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ4, new cjs.Rectangle(0,0,240,323), null);


(lib.Символ3 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.TV_s();
	this.instance.parent = this;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ3, new cjs.Rectangle(0,0,325,317), null);


(lib.Символ2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#1428A0").s().p("Ag/BQIAAgXIBHAAIAAAXQAAAMAKAGQAJAHANAAQALAAAHgGQAGgEAAgHIAAgYQgHgRg5ggQg3gfgIgfIAAgnQAKhBBVAAQBgABAABHIAAAQIhIAAIAAgQQAAgYgYABQgMAAgGAEQgGAFAAAHIAAAPQADASA6AhQA6AhAJAjIAAAwQAAAhgeARQgZAOgpAAQhnAAAAhQgADQBQIAAjfIBIAAIAADXQAAAHAGAIQAHAJALAAQALAAAHgJQAGgIAAgHIAAjXIBIAAIAADfQAAAogbASQgXAPgugBQhVAAgLhIgAvnBIIAAgXIBQAAIAAAXQAAAMAKAGQAJAHANgBQALABAHgGQAGgFAAgGIAAgXQgHgSg5ghQg4gegIgfIAAgnQAAgiAegRQAZgOApAAQBgAAAABIIAAAYIhIAAIAAgQQAAgYgYABQgMAAgGAEQgGAFAAAHIAAAPQADATA6AgQA6AeAJAeIAAAwQgGAigfARQgbAOgogBQhoAAAAhQgAM6CCQgcgSgGgoIAAiXQAFgnAggSQAagPApAAQAtAAAZAPQAcARAGAoIAAAYIhIAAIAAgYIgKgPQgHgJgPAAQgQAAgJAJQgHAHAAAIIAACXQAEAFAGALQAHAJAPgBQAQABAJgJQAHgIAAgIIAAgwIggAAIAAguIBoAAIAABeQgFAnggATQgaAOgpAAQgtAAgZgOgAjfCQIAAkHIgwEHIhIAAIgwkHIAAEHIhIAAIAIkfIB4AAIAgDfIAojfIBoAAIAIEfgApHCQIgokHIgoEHIhQAAIA4kfICAAAIA4EfgAJwCIIhIjvIAIDvIhIAAIAAkXIBoAAIBADnIAAjnIBIAAIAAEXg");
	this.shape.setTransform(128.1,22.5);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

}).prototype = getMCSymbolPrototype(lib.Символ2, new cjs.Rectangle(28.1,6.5,200,32), null);


(lib.Символ7 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_1
	this.instance = new lib.Символ10("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(269,21.4,1,1,0,0,0,100,21.4);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:101,alpha:1},19,cjs.Ease.cubicInOut).wait(11));

	// Слой_2
	this.instance_1 = new lib.Символ11("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(263,67.9,1,1,0,0,0,95,23.9);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({x:95,alpha:1},19,cjs.Ease.cubicInOut).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(169,0,200,42.9);


(lib.Символ5 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.instance = new lib.Символ13("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(240.4,21.1,1,1,0,0,0,75.5,9.8);
	this.instance.alpha = 0;

	this.timeline.addTween(cjs.Tween.get(this.instance).to({x:78.6,alpha:1},14,cjs.Ease.get(1)).wait(14));

	// Слой_3
	this.instance_1 = new lib.Символ14("synched",0);
	this.instance_1.parent = this;
	this.instance_1.setTransform(244.5,45.5,1,1,0,0,0,80.7,5.3);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(11).to({_off:false},0).to({x:82.8,alpha:1},16,cjs.Ease.get(1)).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,315.8,56.6);


(lib.banner = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_9
	this.instance = new lib.Символ20("synched",0);
	this.instance.parent = this;
	this.instance.setTransform(120.5,387,1,1,0,0,0,112.5,30);
	this.instance.alpha = 0;
	this.instance._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(14).to({_off:false},0).to({alpha:0.551},25,cjs.Ease.get(1)).wait(147).to({startPosition:0},0).to({alpha:0},17,cjs.Ease.get(-1)).wait(1));

	// Слой_3
	this.instance_1 = new lib.Символ3();
	this.instance_1.parent = this;
	this.instance_1.setTransform(343.5,97.2,0.492,0.492,0,0,0,150.1,146.3);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(10).to({_off:false},0).to({x:118.5},39,cjs.Ease.get(1)).wait(137).to({alpha:0},17,cjs.Ease.get(-1)).wait(1));

	// Слой_10
	this.instance_2 = new lib.Символ5("synched",0,false);
	this.instance_2.parent = this;
	this.instance_2.setTransform(121.1,213.1,1.169,1.169,0,0,0,83.1,28.3);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(34).to({_off:false},0).wait(44).to({startPosition:27},0).to({y:193.1,alpha:0},10,cjs.Ease.cubicInOut).to({_off:true},1).wait(115));

	// Слой_11
	this.instance_3 = new lib.Символ6();
	this.instance_3.parent = this;
	this.instance_3.setTransform(-48.5,265.5,1,1,0,0,0,57.5,9.5);
	this.instance_3.alpha = 0;
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(61).to({_off:false},0).to({x:81.5,alpha:1},14,cjs.Ease.get(1)).wait(5).to({y:201.5},12,cjs.Ease.cubicInOut).wait(94).to({alpha:0},17,cjs.Ease.get(-1)).wait(1));

	// Слой_7
	this.instance_4 = new lib.Символ7("synched",0,false);
	this.instance_4.parent = this;
	this.instance_4.setTransform(124.5,260.6,1,1,0,0,0,99.5,43.6);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(85).to({_off:false},0).wait(101).to({startPosition:29},0).to({alpha:0},17,cjs.Ease.get(-1)).wait(1));

	// Слой_13
	this.instance_5 = new lib.Символ12("synched",0);
	this.instance_5.parent = this;
	this.instance_5.setTransform(115.4,114.9,1.267,0.591,-5.4,0,0,141.4,141.3);
	this.instance_5.alpha = 0;
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(34).to({_off:false},0).to({alpha:0.109},25,cjs.Ease.get(-1)).wait(127).to({startPosition:0},0).to({alpha:0},11,cjs.Ease.get(-1)).wait(7));

	// Слой_2
	this.instance_6 = new lib.ClipGroup();
	this.instance_6.parent = this;
	this.instance_6.setTransform(120.5,340.8,0.401,0.401,0,0,0,240.5,34.4);
	this.instance_6.alpha = 0;
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(10).to({_off:false},0).to({alpha:0.602},24,cjs.Ease.get(1)).wait(152).to({alpha:0},17).wait(1));

	// Слой_6
	this.instance_7 = new lib.Символ4();
	this.instance_7.parent = this;
	this.instance_7.setTransform(120,202.1,1,1.282,0,0,0,120,161.4);

	this.timeline.addTween(cjs.Tween.get(this.instance_7).to({y:250.1},34,cjs.Ease.cubicInOut).wait(145).to({y:202.1},24,cjs.Ease.get(-1)).wait(1));

	// Слой_8
	this.instance_8 = new lib.Символ9("synched",0);
	this.instance_8.parent = this;
	this.instance_8.setTransform(224.1,18.2,1,1,0,0,0,11.1,13.2);

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(204));

	// 圖層 1
	this.instance_9 = new lib.Символ2();
	this.instance_9.parent = this;
	this.instance_9.setTransform(54.4,47.8,0.423,0.423,0,0,0,100,16.1);
	this.instance_9.alpha = 0;
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(5).to({_off:false},0).to({y:17.8,alpha:1},24,cjs.Ease.get(1)).wait(175));

	// Слой_1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AyvfQMAAAg+fMAlfAAAMAAAA+fg");
	this.shape.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(204));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,-4.8,240,414);


// stage content:
(lib._240x400 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Слой_2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#000000").ss(2,1,1).p("Ayv/PMAlfAAAMAAAA+fMglfAAAg");
	this.shape.setTransform(120,200);

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1));

	// Слой_1
	this.instance = new lib.banner();
	this.instance.parent = this;
	this.instance.setTransform(120,200,1,1,0,0,0,120,200);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(119,195.2,242,414);
// library properties:
lib.properties = {
	id: 'C6A00BBDD0286844BAA69EAD3B3A70D2',
	width: 240,
	height: 400,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"./TV_s.png", id:"TV_s"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['C6A00BBDD0286844BAA69EAD3B3A70D2'] = {
	getStage: function() { return exportRoot.getStage(); },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}



})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;